In [2]:
!pip install -q openai pydantic pandas tqdm

In [3]:
import os
from getpass import getpass
from google.colab import userdata
os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")

In [4]:
from __future__ import annotations

import csv
import json
import os
import time
from pathlib import Path
from typing import Iterable

import pandas as pd
from openai import OpenAI
from pydantic import BaseModel, Field, field_validator
from tqdm.auto import tqdm


GENERATOR_MODEL = "gpt-5.4-mini"

EXPORT_DIR = Path("/content/airplane_translation_dataset")
EXPORT_DIR.mkdir(parents=True, exist_ok=True)

RAW_JSONL_PATH = EXPORT_DIR / "raw_pairs.jsonl"
CSV_PATH = EXPORT_DIR / "pairs.csv"
FINE_TUNE_JSONL_PATH = EXPORT_DIR / "fine_tune_chat.jsonl"

client = OpenAI()

In [5]:
DOMAINS = [
    "greetings_and_basic_conversation",
    "seat_and_cabin_location",
    "toilet_and_lavatory",
    "food_and_drink",
    "comfort_and_cabin_needs",
    "flight_time_delay_and_arrival",
    "baggage_and_personal_items",
    "children_and_family",
    "pets_and_service_animals",
    "health_and_medical_issues",
    "emergency_situations",
    "safety_instructions_and_announcements",
    "boarding_and_pre_flight",
    "immigration_forms_and_documents",
    "payment_and_onboard_purchases",
    "complaints_and_problem_reporting",
    "accessibility_and_special_assistance",
    "language_difficulty_and_translation_support",
]

DIRECTIONS = [
    ("English", "Turkish"),
    ("Turkish", "English"),
]

SPEAKERS = {
    "passenger",
    "cabin_crew",
    "gate_agent",
    "pilot",
    "airport_staff",
}

TONES = {
    "polite",
    "neutral",
    "formal",
    "urgent",
    "reassuring",
}

DIFFICULTIES = {
    "A1",
    "A2",
    "B1",
}

In [6]:
TRANSLATION_SYSTEM_PROMPT = """You are a Turkish-English translation assistant specialized in airplane, airport boarding, cabin, passenger, and flight-related situations.

Your task is to translate the user's sentence between Turkish and English.

Rules:
- If the input is Turkish, translate it into natural English.
- If the input is English, translate it into natural Turkish.
- Preserve the meaning, politeness level, urgency, and speaker intent.
- Use simple, clear, practical language suitable for airplane passengers and cabin crew.
- Do not add explanations.
- Do not answer the user's request.
- Do not roleplay.
- Only return the translated sentence.
- For emergency sentences, keep the translation direct and accurate.
- For polite requests, preserve politeness naturally.
- For announcements or crew instructions, use clear formal language.
"""

In [7]:
GENERATOR_SYSTEM_PROMPT = """You are a bilingual Turkish-English dataset generation assistant.

Your task is to create high-quality parallel translation examples for a small language model that will be fine-tuned for airplane-related Turkish-English translation.

The model will translate both ways:
- English to Turkish
- Turkish to English

Generate natural, realistic, domain-specific sentence pairs.

Requirements:
- Sentences must be useful in airplane, boarding, cabin, passenger, crew, airport-gate, flight-delay, luggage, food, toilet, child, pet, accessibility, health, emergency, and basic conversation scenarios.
- Include both passenger-to-crew and crew-to-passenger sentences.
- Include simple A1/A2 sentences, but also some B1 practical sentences.
- Keep most examples short and realistic.
- Avoid long paragraphs.
- Preserve natural spoken language.
- Include polite, neutral, urgent, formal, and reassuring tones where appropriate.
- Emergency examples must be direct and medically/logistically useful.
- Turkish must sound natural to native Turkish speakers.
- English must sound natural to native English speakers.
- Do not overuse literal translation.
- Do not include explanations outside the structured data.
"""

In [8]:
class TranslationExample(BaseModel):
    domain: str
    scenario: str
    source_language: str
    target_language: str
    source_text: str
    target_text: str
    speaker: str
    listener: str
    difficulty: str
    tone: str
    tags: list[str] = Field(default_factory=list)

    @field_validator("source_text", "target_text", "scenario")
    @classmethod
    def validate_non_empty_text(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Text cannot be empty")
        return value

    @field_validator("source_language", "target_language")
    @classmethod
    def validate_language(cls, value: str) -> str:
        allowed = {"Turkish", "English"}
        if value not in allowed:
            raise ValueError(f"Language must be one of {allowed}")
        return value

    @field_validator("difficulty")
    @classmethod
    def validate_difficulty(cls, value: str) -> str:
        if value not in DIFFICULTIES:
            raise ValueError(f"Difficulty must be one of {DIFFICULTIES}")
        return value

    @field_validator("tone")
    @classmethod
    def validate_tone(cls, value: str) -> str:
        if value not in TONES:
            raise ValueError(f"Tone must be one of {TONES}")
        return value

    @field_validator("speaker", "listener")
    @classmethod
    def validate_speaker_listener(cls, value: str) -> str:
        if value not in SPEAKERS:
            raise ValueError(f"Speaker/listener must be one of {SPEAKERS}")
        return value


class TranslationBatch(BaseModel):
    examples: list[TranslationExample]

In [9]:
TRANSLATION_BATCH_JSON_SCHEMA = {
    "name": "translation_batch",
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "examples": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "domain": {"type": "string"},
                        "scenario": {"type": "string"},
                        "source_language": {
                            "type": "string",
                            "enum": ["Turkish", "English"],
                        },
                        "target_language": {
                            "type": "string",
                            "enum": ["Turkish", "English"],
                        },
                        "source_text": {"type": "string"},
                        "target_text": {"type": "string"},
                        "speaker": {
                            "type": "string",
                            "enum": [
                                "passenger",
                                "cabin_crew",
                                "gate_agent",
                                "pilot",
                                "airport_staff",
                            ],
                        },
                        "listener": {
                            "type": "string",
                            "enum": [
                                "passenger",
                                "cabin_crew",
                                "gate_agent",
                                "pilot",
                                "airport_staff",
                            ],
                        },
                        "difficulty": {
                            "type": "string",
                            "enum": ["A1", "A2", "B1"],
                        },
                        "tone": {
                            "type": "string",
                            "enum": [
                                "polite",
                                "neutral",
                                "formal",
                                "urgent",
                                "reassuring",
                            ],
                        },
                        "tags": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                    },
                    "required": [
                        "domain",
                        "scenario",
                        "source_language",
                        "target_language",
                        "source_text",
                        "target_text",
                        "speaker",
                        "listener",
                        "difficulty",
                        "tone",
                        "tags",
                    ],
                },
            }
        },
        "required": ["examples"],
    },
    "strict": True,
}

In [10]:
def build_generation_prompt(
    *,
    domain: str,
    count: int,
    source_language: str,
    target_language: str,
) -> str:
    return f"""
Generate {count} Turkish-English translation dataset examples.

Domain:
{domain}

Direction:
{source_language} to {target_language}

Each example must match this meaning:
- source_text is written in {source_language}
- target_text is the natural translation in {target_language}

Requirements for this batch:
- Use the exact domain value: {domain}
- Generate varied scenarios inside this domain.
- Avoid repeating the same sentence structure too much.
- Include realistic airplane/cabin/boarding context.
- Keep sentences short enough for a 1B model fine-tuning dataset.
- Include passenger and staff perspectives when suitable.
- Do not generate unrelated airport hotel/taxi/tourism examples unless directly connected to the flight journey.
"""

In [11]:
def call_generator(
    *,
    domain: str,
    count: int,
    source_language: str,
    target_language: str,
    max_retries: int = 3,
) -> TranslationBatch:
    user_prompt = build_generation_prompt(
        domain=domain,
        count=count,
        source_language=source_language,
        target_language=target_language,
    )

    last_error = None

    for attempt in range(1, max_retries + 1):
        try:
            response = client.responses.create(
                model=GENERATOR_MODEL,
                input=[
                    {
                        "role": "system",
                        "content": GENERATOR_SYSTEM_PROMPT,
                    },
                    {
                        "role": "user",
                        "content": user_prompt,
                    },
                ],
                text={
                    "format": {
                        "type": "json_schema",
                        **TRANSLATION_BATCH_JSON_SCHEMA,
                    }
                },
            )

            raw_text = response.output_text
            data = json.loads(raw_text)
            batch = TranslationBatch.model_validate(data)

            fixed_examples = []
            for example in batch.examples:
                fixed_examples.append(
                    example.model_copy(
                        update={
                            "domain": domain,
                            "source_language": source_language,
                            "target_language": target_language,
                        }
                    )
                )

            return TranslationBatch(examples=fixed_examples)

        except Exception as exc:
            last_error = exc
            print(f"Attempt {attempt} failed for {domain} {source_language}->{target_language}: {exc}")
            time.sleep(2 * attempt)

    raise RuntimeError(
        f"Failed after {max_retries} retries for {domain} {source_language}->{target_language}"
    ) from last_error

In [12]:
def normalize_text(value: str) -> str:
    return " ".join(value.lower().strip().split())


def dedupe_examples(
    examples: Iterable[TranslationExample],
) -> list[TranslationExample]:
    seen = set()
    deduped = []

    for example in examples:
        key = (
            example.source_language,
            example.target_language,
            normalize_text(example.source_text),
            normalize_text(example.target_text),
        )

        if key in seen:
            continue

        seen.add(key)
        deduped.append(example)

    return deduped


def basic_quality_filter(
    examples: Iterable[TranslationExample],
) -> list[TranslationExample]:
    filtered = []

    for example in examples:
        source_len = len(example.source_text.split())
        target_len = len(example.target_text.split())

        if source_len < 1 or target_len < 1:
            continue

        if source_len > 30 or target_len > 35:
            continue

        if example.source_text == example.target_text:
            continue

        filtered.append(example)

    return filtered

In [13]:
def save_raw_jsonl(examples: list[TranslationExample]) -> None:
    with RAW_JSONL_PATH.open("w", encoding="utf-8") as file:
        for example in examples:
            file.write(example.model_dump_json() + "\n")


def save_csv(examples: list[TranslationExample]) -> None:
    rows = []

    for example in examples:
        row = example.model_dump()
        row["tags"] = ",".join(example.tags)
        rows.append(row)

    df = pd.DataFrame(rows)
    df.to_csv(CSV_PATH, index=False, encoding="utf-8")


def build_fine_tune_record(example: TranslationExample) -> dict:
    if example.target_language == "Turkish":
        instruction = "Translate to Turkish:"
    else:
        instruction = "Translate to English:"

    return {
        "messages": [
            {
                "role": "system",
                "content": TRANSLATION_SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": f"{instruction} {example.source_text}",
            },
            {
                "role": "assistant",
                "content": example.target_text,
            },
        ]
    }


def save_fine_tune_jsonl(examples: list[TranslationExample]) -> None:
    with FINE_TUNE_JSONL_PATH.open("w", encoding="utf-8") as file:
        for example in examples:
            record = build_fine_tune_record(example)
            file.write(json.dumps(record, ensure_ascii=False) + "\n")


def save_all_exports(examples: list[TranslationExample]) -> None:
    save_raw_jsonl(examples)
    save_csv(examples)
    save_fine_tune_jsonl(examples)

    print("Saved:")
    print(RAW_JSONL_PATH)
    print(CSV_PATH)
    print(FINE_TUNE_JSONL_PATH)

In [ ]:
SMOKE_TEST_DOMAINS = [
    "greetings_and_basic_conversation",
    "food_and_drink",
    "emergency_situations",
]

examples = []

for domain in tqdm(SMOKE_TEST_DOMAINS):
    for source_language, target_language in DIRECTIONS:
        batch = call_generator(
            domain=domain,
            count=5,
            source_language=source_language,
            target_language=target_language,
        )
        examples.extend(batch.examples)

examples = basic_quality_filter(examples)
examples = dedupe_examples(examples)

save_all_exports(examples)

len(examples)

  0%|          | 0/3 [00:00<?, ?it/s]

Saved:
/content/airplane_translation_dataset/raw_pairs.jsonl
/content/airplane_translation_dataset/pairs.csv
/content/airplane_translation_dataset/fine_tune_chat.jsonl

30

In [ ]:
TARGET_PER_DOMAIN_PER_DIRECTION = 500
BATCH_SIZE = 50
SLEEP_SECONDS = 0.5

all_examples = []

for domain in tqdm(DOMAINS, desc="Domains"):
    for source_language, target_language in DIRECTIONS:
        generated_for_pair = 0

        pair_bar = tqdm(
            total=TARGET_PER_DOMAIN_PER_DIRECTION,
            desc=f"{domain} {source_language}->{target_language}",
            leave=False,
        )

        while generated_for_pair < TARGET_PER_DOMAIN_PER_DIRECTION:
            remaining = TARGET_PER_DOMAIN_PER_DIRECTION - generated_for_pair
            current_batch_size = min(BATCH_SIZE, remaining)

            batch = call_generator(
                domain=domain,
                count=current_batch_size,
                source_language=source_language,
                target_language=target_language,
            )

            batch_examples = batch.examples
            all_examples.extend(batch_examples)

            generated_for_pair += len(batch_examples)
            pair_bar.update(len(batch_examples))

            print(
                f"{domain} {source_language}->{target_language}: "
                f"requested={current_batch_size}, received={len(batch_examples)}, "
                f"total_for_pair={generated_for_pair}"
            )

            time.sleep(SLEEP_SECONDS)

        pair_bar.close()

all_examples = basic_quality_filter(all_examples)
all_examples = dedupe_examples(all_examples)

save_all_exports(all_examples)

print("Final example count:", len(all_examples))

  0%|          | 0/18 [00:00<?, ?it/s]

Saved:
/content/airplane_translation_dataset/raw_pairs.jsonl
/content/airplane_translation_dataset/pairs.csv
/content/airplane_translation_dataset/fine_tune_chat.jsonl
Final example count: 3436

In [14]:
SCENARIO_MAP = {
    "greetings_and_basic_conversation": [
        "basic greetings",
        "asking for help",
        "saying thank you and goodbye",
        "asking someone to repeat slowly",
        "simple misunderstanding phrases",
    ],
    "seat_and_cabin_location": [
        "finding assigned seat",
        "someone sitting in passenger seat",
        "window aisle and middle seat requests",
        "family sitting together",
        "overhead bin and under-seat bag placement",
        "seatbelt and aisle clearance instructions",
    ],
    "toilet_and_lavatory": [
        "asking where the toilet is",
        "asking permission to use the toilet",
        "toilet occupied or unavailable",
        "toilet problem reporting",
        "seatbelt sign and toilet restriction",
        "urgent toilet need",
    ],
    "food_and_drink": [
        "asking for water tea coffee or juice",
        "meal choice chicken beef fish pasta",
        "vegetarian vegan halal and dietary requests",
        "food allergy warnings",
        "asking for bread napkin or extra drink",
        "complaining about cold or missing food",
        "special meal already ordered",
    ],
    "comfort_and_cabin_needs": [
        "asking for blanket or pillow",
        "feeling cold or hot",
        "air vent reading light and tray table",
        "screen headphones and entertainment problems",
        "seat recline or broken seat",
        "asking for sick bag",
    ],
    "flight_time_delay_and_arrival": [
        "asking flight duration",
        "asking arrival and landing time",
        "delay and waiting explanations",
        "connecting flight concerns",
        "local time at destination",
        "gate and baggage claim after landing",
    ],
    "baggage_and_personal_items": [
        "placing cabin bag",
        "bag does not fit",
        "lost phone wallet passport or headphones",
        "forgotten item on plane",
        "wrong bag or damaged suitcase",
        "lost luggage reporting",
    ],
    "children_and_family": [
        "traveling with child",
        "family seating requests",
        "baby milk and bottle warming",
        "child meal and baby food",
        "child is sick afraid or crying",
        "stroller and diaper change needs",
    ],
    "pets_and_service_animals": [
        "traveling with pet in cabin",
        "service animal explanation",
        "pet carrier under seat",
        "pet is anxious",
        "giving water to pet",
        "pet documents",
    ],
    "health_and_medical_issues": [
        "feeling sick dizzy or weak",
        "headache stomach pain and nausea",
        "asking for medicine or water",
        "anxiety and panic",
        "pregnancy and diabetes",
        "asking for doctor or nurse",
        "breathing difficulty but not full emergency",
    ],
    "emergency_situations": [
        "urgent help request",
        "cannot breathe",
        "chest pain",
        "someone fainted",
        "child choking",
        "smoke fire or burning smell",
        "crew emergency instructions",
        "evacuation related phrases",
        "oxygen mask and life vest instructions",
    ],
    "safety_instructions_and_announcements": [
        "fasten seatbelt instruction",
        "seat upright and tray table closed",
        "window shade and electronic devices",
        "seatbelt sign on",
        "do not block aisle",
        "oxygen mask announcement",
        "life vest announcement",
        "emergency exits announcement",
    ],
    "boarding_and_pre_flight": [
        "boarding pass check",
        "finding correct gate or plane",
        "priority boarding",
        "assistance boarding",
        "seat number changed",
        "passport check",
        "boarding group and queue",
    ],
    "immigration_forms_and_documents": [
        "asking about forms",
        "help filling form",
        "passport visa and residence permit",
        "destination address",
        "asking for pen",
        "lost passport",
    ],
    "payment_and_onboard_purchases": [
        "asking price",
        "paying by card or cash",
        "buying wifi",
        "buying headphones or snacks",
        "asking if something is free",
        "receipt request",
        "card not working",
        "canceling purchase",
    ],
    "complaints_and_problem_reporting": [
        "general problem reporting",
        "broken seat screen or headphones",
        "uncomfortable situation",
        "disturbing passenger",
        "noise complaint",
        "someone took my bag",
        "asking crew to solve issue",
    ],
    "accessibility_and_special_assistance": [
        "wheelchair assistance",
        "cannot walk far",
        "hearing or vision difficulty",
        "help reading information",
        "extra time needed",
        "assistance getting to seat",
        "help after landing",
    ],
    "language_difficulty_and_translation_support": [
        "please speak slowly",
        "please write it down",
        "I do not understand Turkish",
        "I do not understand English",
        "can you translate this",
        "what does this mean",
        "how do I say this",
        "use simple words",
    ],
}

In [15]:
PRODUCTION_TARGETS = {
    "greetings_and_basic_conversation": 3000,
    "seat_and_cabin_location": 8000,
    "toilet_and_lavatory": 5000,
    "food_and_drink": 9000,
    "comfort_and_cabin_needs": 7000,
    "flight_time_delay_and_arrival": 8000,
    "baggage_and_personal_items": 7000,
    "children_and_family": 6000,
    "pets_and_service_animals": 3500,
    "health_and_medical_issues": 9000,
    "emergency_situations": 12000,
    "safety_instructions_and_announcements": 10000,
    "boarding_and_pre_flight": 7000,
    "immigration_forms_and_documents": 5000,
    "payment_and_onboard_purchases": 4000,
    "complaints_and_problem_reporting": 6000,
    "accessibility_and_special_assistance": 6000,
    "language_difficulty_and_translation_support": 4000,
}

BATCH_SIZE = 40
SLEEP_SECONDS = 0.7
MAX_RETRIES = 4

DIRECTIONS = [
    ("English", "Turkish"),
    ("Turkish", "English"),
]

In [16]:
from pathlib import Path
import json
import time
import hashlib
import pandas as pd
from tqdm.auto import tqdm

EXPORT_DIR = Path("/content/airplane_translation_dataset")
CHUNK_DIR = EXPORT_DIR / "scenario_chunks"
CHECKPOINT_DIR = EXPORT_DIR / "checkpoints"
FINAL_DIR = EXPORT_DIR / "final"

for path in [EXPORT_DIR, CHUNK_DIR, CHECKPOINT_DIR, FINAL_DIR]:
    path.mkdir(parents=True, exist_ok=True)

RAW_MERGED_JSONL_PATH = FINAL_DIR / "raw_pairs_merged.jsonl"
CSV_MERGED_PATH = FINAL_DIR / "pairs_merged.csv"
FINE_TUNE_JSONL_PATH = FINAL_DIR / "fine_tune_chat.jsonl"
PROGRESS_PATH = EXPORT_DIR / "generation_progress.json"

In [17]:
def safe_name(value: str) -> str:
    return (
        value.lower()
        .replace(" ", "_")
        .replace("/", "_")
        .replace("-", "_")
        .replace("__", "_")
    )


def example_hash(example) -> str:
    raw = "|".join(
        [
            example.domain,
            getattr(example, "scenario_group", ""),
            example.source_language,
            example.target_language,
            example.source_text.strip().lower(),
            example.target_text.strip().lower(),
        ]
    )
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def chunk_path_for(domain: str, scenario: str, source_language: str, target_language: str) -> Path:
    filename = (
        f"{safe_name(domain)}__"
        f"{safe_name(scenario)}__"
        f"{safe_name(source_language)}_to_{safe_name(target_language)}.jsonl"
    )
    return CHUNK_DIR / filename


def checkpoint_path_for(domain: str, scenario: str, source_language: str, target_language: str) -> Path:
    filename = (
        f"{safe_name(domain)}__"
        f"{safe_name(scenario)}__"
        f"{safe_name(source_language)}_to_{safe_name(target_language)}.checkpoint.jsonl"
    )
    return CHECKPOINT_DIR / filename

In [18]:
def load_progress() -> dict:
    if not PROGRESS_PATH.exists():
        return {}

    with PROGRESS_PATH.open("r", encoding="utf-8") as file:
        return json.load(file)


def save_progress(progress: dict) -> None:
    with PROGRESS_PATH.open("w", encoding="utf-8") as file:
        json.dump(progress, file, ensure_ascii=False, indent=2)


def progress_key(domain: str, scenario: str, source_language: str, target_language: str) -> str:
    return f"{domain}::{scenario}::{source_language}->{target_language}"


def count_jsonl_rows(path: Path) -> int:
    if not path.exists():
        return 0

    with path.open("r", encoding="utf-8") as file:
        return sum(1 for _ in file)

In [19]:
def build_generation_prompt(
    *,
    domain: str,
    scenario_group: str,
    count: int,
    source_language: str,
    target_language: str,
) -> str:
    return f"""
Generate {count} Turkish-English translation dataset examples.

Domain:
{domain}

Scenario group:
{scenario_group}

Direction:
{source_language} to {target_language}

Each example must match this meaning:
- source_text is written in {source_language}
- target_text is the natural translation in {target_language}

Requirements for this batch:
- Use the exact domain value: {domain}
- Focus specifically on this scenario group: {scenario_group}
- Generate varied, realistic airplane-related sentences.
- Avoid repeating the same sentence structure too much.
- Include both passenger and staff perspectives when suitable.
- Keep most sentences short enough for a 1B model fine-tuning dataset.
- Include natural spoken Turkish and natural spoken English.
- Preserve politeness, urgency, and intent.
- Do not include explanations.
- Do not include unrelated tourism, hotel, taxi, or city examples unless directly connected to flight handling.
"""

In [20]:
from pydantic import BaseModel, Field, field_validator

SPEAKERS = {
    "passenger",
    "cabin_crew",
    "gate_agent",
    "pilot",
    "airport_staff",
}

TONES = {
    "polite",
    "neutral",
    "formal",
    "urgent",
    "reassuring",
}

DIFFICULTIES = {
    "A1",
    "A2",
    "B1",
}


class TranslationExample(BaseModel):
    domain: str
    scenario_group: str
    scenario: str
    source_language: str
    target_language: str
    source_text: str
    target_text: str
    speaker: str
    listener: str
    difficulty: str
    tone: str
    tags: list[str] = Field(default_factory=list)

    @field_validator("source_text", "target_text", "scenario", "scenario_group")
    @classmethod
    def validate_non_empty_text(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Text cannot be empty")
        return value

    @field_validator("source_language", "target_language")
    @classmethod
    def validate_language(cls, value: str) -> str:
        allowed = {"Turkish", "English"}
        if value not in allowed:
            raise ValueError(f"Language must be one of {allowed}")
        return value

    @field_validator("difficulty")
    @classmethod
    def validate_difficulty(cls, value: str) -> str:
        if value not in DIFFICULTIES:
            raise ValueError(f"Difficulty must be one of {DIFFICULTIES}")
        return value

    @field_validator("tone")
    @classmethod
    def validate_tone(cls, value: str) -> str:
        if value not in TONES:
            raise ValueError(f"Tone must be one of {TONES}")
        return value

    @field_validator("speaker", "listener")
    @classmethod
    def validate_speaker_listener(cls, value: str) -> str:
        if value not in SPEAKERS:
            raise ValueError(f"Speaker/listener must be one of {SPEAKERS}")
        return value


class TranslationBatch(BaseModel):
    examples: list[TranslationExample]

In [21]:
TRANSLATION_BATCH_JSON_SCHEMA = {
    "name": "translation_batch",
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "examples": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "domain": {"type": "string"},
                        "scenario_group": {"type": "string"},
                        "scenario": {"type": "string"},
                        "source_language": {
                            "type": "string",
                            "enum": ["Turkish", "English"],
                        },
                        "target_language": {
                            "type": "string",
                            "enum": ["Turkish", "English"],
                        },
                        "source_text": {"type": "string"},
                        "target_text": {"type": "string"},
                        "speaker": {
                            "type": "string",
                            "enum": [
                                "passenger",
                                "cabin_crew",
                                "gate_agent",
                                "pilot",
                                "airport_staff",
                            ],
                        },
                        "listener": {
                            "type": "string",
                            "enum": [
                                "passenger",
                                "cabin_crew",
                                "gate_agent",
                                "pilot",
                                "airport_staff",
                            ],
                        },
                        "difficulty": {
                            "type": "string",
                            "enum": ["A1", "A2", "B1"],
                        },
                        "tone": {
                            "type": "string",
                            "enum": [
                                "polite",
                                "neutral",
                                "formal",
                                "urgent",
                                "reassuring",
                            ],
                        },
                        "tags": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                    },
                    "required": [
                        "domain",
                        "scenario_group",
                        "scenario",
                        "source_language",
                        "target_language",
                        "source_text",
                        "target_text",
                        "speaker",
                        "listener",
                        "difficulty",
                        "tone",
                        "tags",
                    ],
                },
            }
        },
        "required": ["examples"],
    },
    "strict": True,
}

In [22]:
def call_generator(
    *,
    domain: str,
    scenario_group: str,
    count: int,
    source_language: str,
    target_language: str,
    max_retries: int = MAX_RETRIES,
) -> TranslationBatch:
    user_prompt = build_generation_prompt(
        domain=domain,
        scenario_group=scenario_group,
        count=count,
        source_language=source_language,
        target_language=target_language,
    )

    last_error = None

    for attempt in range(1, max_retries + 1):
        try:
            response = client.responses.create(
                model=GENERATOR_MODEL,
                input=[
                    {
                        "role": "system",
                        "content": GENERATOR_SYSTEM_PROMPT,
                    },
                    {
                        "role": "user",
                        "content": user_prompt,
                    },
                ],
                text={
                    "format": {
                        "type": "json_schema",
                        **TRANSLATION_BATCH_JSON_SCHEMA,
                    }
                },
            )

            data = json.loads(response.output_text)
            batch = TranslationBatch.model_validate(data)

            fixed_examples = []
            for example in batch.examples:
                fixed_examples.append(
                    example.model_copy(
                        update={
                            "domain": domain,
                            "scenario_group": scenario_group,
                            "source_language": source_language,
                            "target_language": target_language,
                        }
                    )
                )

            return TranslationBatch(examples=fixed_examples)

        except Exception as exc:
            last_error = exc
            print(
                f"Attempt {attempt} failed: "
                f"{domain} / {scenario_group} / {source_language}->{target_language}: {exc}"
            )
            time.sleep(2 * attempt)

    raise RuntimeError(
        f"Failed after {max_retries} retries: "
        f"{domain} / {scenario_group} / {source_language}->{target_language}"
    ) from last_error

In [23]:
def append_jsonl(path: Path, examples: list[TranslationExample]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("a", encoding="utf-8") as file:
        for example in examples:
            file.write(example.model_dump_json() + "\n")


def read_jsonl_examples(path: Path) -> list[TranslationExample]:
    if not path.exists():
        return []

    examples = []
    with path.open("r", encoding="utf-8") as file:
        for line in file:
            if line.strip():
                examples.append(TranslationExample.model_validate_json(line))

    return examples

In [24]:
def normalize_text(value: str) -> str:
    return " ".join(value.lower().strip().split())


def basic_quality_filter(examples: list[TranslationExample]) -> list[TranslationExample]:
    filtered = []

    for example in examples:
        source_words = example.source_text.split()
        target_words = example.target_text.split()

        if not source_words or not target_words:
            continue

        if len(source_words) > 35 or len(target_words) > 40:
            continue

        if normalize_text(example.source_text) == normalize_text(example.target_text):
            continue

        filtered.append(example)

    return filtered


def dedupe_examples(examples: list[TranslationExample]) -> list[TranslationExample]:
    seen = set()
    deduped = []

    for example in examples:
        key = (
            example.source_language,
            example.target_language,
            normalize_text(example.source_text),
            normalize_text(example.target_text),
        )

        if key in seen:
            continue

        seen.add(key)
        deduped.append(example)

    return deduped

In [25]:
def scenario_target_for(domain: str, scenario: str) -> int:
    domain_target = PRODUCTION_TARGETS[domain]
    scenario_count = len(SCENARIO_MAP[domain])

    # Total domain target is split across both directions.
    # Example: domain target 8000 -> 4000 EN->TR, 4000 TR->EN.
    per_direction_domain_target = domain_target // 2

    base = per_direction_domain_target // scenario_count
    return max(base, BATCH_SIZE)

In [ ]:
def generate_production_dataset() -> None:
    progress = load_progress()

    total_tasks = sum(len(scenarios) * len(DIRECTIONS) for scenarios in SCENARIO_MAP.values())

    task_bar = tqdm(total=total_tasks, desc="Scenario-direction tasks")

    for domain, scenarios in SCENARIO_MAP.items():
        for scenario_group in scenarios:
            for source_language, target_language in DIRECTIONS:
                key = progress_key(domain, scenario_group, source_language, target_language)

                target_count = scenario_target_for(domain, scenario_group)
                final_chunk_path = chunk_path_for(
                    domain,
                    scenario_group,
                    source_language,
                    target_language,
                )
                checkpoint_path = checkpoint_path_for(
                    domain,
                    scenario_group,
                    source_language,
                    target_language,
                )

                existing_count = count_jsonl_rows(final_chunk_path)

                if existing_count >= target_count:
                    progress[key] = {
                        "status": "complete",
                        "target_count": target_count,
                        "current_count": existing_count,
                        "chunk_path": str(final_chunk_path),
                        "checkpoint_path": str(checkpoint_path),
                    }
                    save_progress(progress)
                    task_bar.update(1)
                    continue

                current_count = existing_count

                pair_bar = tqdm(
                    total=target_count,
                    initial=current_count,
                    desc=f"{domain} / {scenario_group} / {source_language}->{target_language}",
                    leave=False,
                )

                while current_count < target_count:
                    remaining = target_count - current_count
                    current_batch_size = min(BATCH_SIZE, remaining)

                    batch = call_generator(
                        domain=domain,
                        scenario_group=scenario_group,
                        count=current_batch_size,
                        source_language=source_language,
                        target_language=target_language,
                    )

                    batch_examples = basic_quality_filter(batch.examples)
                    batch_examples = dedupe_examples(batch_examples)

                    append_jsonl(checkpoint_path, batch_examples)
                    append_jsonl(final_chunk_path, batch_examples)

                    current_count += len(batch_examples)
                    pair_bar.update(len(batch_examples))

                    progress[key] = {
                        "status": "running",
                        "target_count": target_count,
                        "current_count": current_count,
                        "chunk_path": str(final_chunk_path),
                        "checkpoint_path": str(checkpoint_path),
                    }
                    save_progress(progress)

                    print(
                        f"{key}: requested={current_batch_size}, "
                        f"accepted={len(batch_examples)}, "
                        f"current={current_count}/{target_count}"
                    )

                    time.sleep(SLEEP_SECONDS)

                progress[key] = {
                    "status": "complete",
                    "target_count": target_count,
                    "current_count": current_count,
                    "chunk_path": str(final_chunk_path),
                    "checkpoint_path": str(checkpoint_path),
                }
                save_progress(progress)

                pair_bar.close()
                task_bar.update(1)

    task_bar.close()


generate_production_dataset()

Scenario-direction tasks:   0%|          | 0/242 [00:00<?, ?it/s]

greetings_and_basic_conversation / basic greetings / English->Turkish:   0%|          | 0/300 [00:00<?, ?it/s]

greetings_and_basic_conversation::basic greetings::English->Turkish: requested=40, accepted=37, current=37/300
greetings_and_basic_conversation::basic greetings::English->Turkish: requested=40, accepted=39, current=76/300
greetings_and_basic_conversation::basic greetings::English->Turkish: requested=40, accepted=39, current=115/300
greetings_and_basic_conversation::basic greetings::English->Turkish: requested=40, accepted=38, current=153/300
greetings_and_basic_conversation::basic greetings::English->Turkish: requested=40, accepted=39, current=192/300
greetings_and_basic_conversation::basic greetings::English->Turkish: requested=40, accepted=41, current=233/300
greetings_and_basic_conversation::basic greetings::English->Turkish: requested=40, accepted=40, current=273/300
greetings_and_basic_conversation::basic greetings::English->Turkish: requested=27, accepted=28, current=301/300

greetings_and_basic_conversation / basic greetings / Turkish->English:   0%|          | 0/300 [00:00<?, ?it/s]

greetings_and_basic_conversation::basic greetings::Turkish->English: requested=40, accepted=38, current=38/300
greetings_and_basic_conversation::basic greetings::Turkish->English: requested=40, accepted=41, current=79/300
greetings_and_basic_conversation::basic greetings::Turkish->English: requested=40, accepted=40, current=119/300
greetings_and_basic_conversation::basic greetings::Turkish->English: requested=40, accepted=38, current=157/300
greetings_and_basic_conversation::basic greetings::Turkish->English: requested=40, accepted=41, current=198/300
greetings_and_basic_conversation::basic greetings::Turkish->English: requested=40, accepted=41, current=239/300
greetings_and_basic_conversation::basic greetings::Turkish->English: requested=40, accepted=37, current=276/300
greetings_and_basic_conversation::basic greetings::Turkish->English: requested=24, accepted=24, current=300/300

greetings_and_basic_conversation / asking for help / English->Turkish:   0%|          | 0/300 [00:00<?, ?it/s]

greetings_and_basic_conversation::asking for help::English->Turkish: requested=40, accepted=42, current=42/300
greetings_and_basic_conversation::asking for help::English->Turkish: requested=40, accepted=38, current=80/300
greetings_and_basic_conversation::asking for help::English->Turkish: requested=40, accepted=43, current=123/300
greetings_and_basic_conversation::asking for help::English->Turkish: requested=40, accepted=38, current=161/300
greetings_and_basic_conversation::asking for help::English->Turkish: requested=40, accepted=39, current=200/300
greetings_and_basic_conversation::asking for help::English->Turkish: requested=40, accepted=40, current=240/300
greetings_and_basic_conversation::asking for help::English->Turkish: requested=40, accepted=39, current=279/300
greetings_and_basic_conversation::asking for help::English->Turkish: requested=21, accepted=21, current=300/300

greetings_and_basic_conversation / asking for help / Turkish->English:   0%|          | 0/300 [00:00<?, ?it/s]

greetings_and_basic_conversation::asking for help::Turkish->English: requested=40, accepted=40, current=40/300
greetings_and_basic_conversation::asking for help::Turkish->English: requested=40, accepted=39, current=79/300
greetings_and_basic_conversation::asking for help::Turkish->English: requested=40, accepted=38, current=117/300
greetings_and_basic_conversation::asking for help::Turkish->English: requested=40, accepted=38, current=155/300
greetings_and_basic_conversation::asking for help::Turkish->English: requested=40, accepted=42, current=197/300
greetings_and_basic_conversation::asking for help::Turkish->English: requested=40, accepted=39, current=236/300
greetings_and_basic_conversation::asking for help::Turkish->English: requested=40, accepted=50, current=286/300
greetings_and_basic_conversation::asking for help::Turkish->English: requested=14, accepted=14, current=300/300

greetings_and_basic_conversation / saying thank you and goodbye / English->Turkish:   0%|          | 0/300 [00…

greetings_and_basic_conversation::saying thank you and goodbye::English->Turkish: requested=40, accepted=40, current=40/300
greetings_and_basic_conversation::saying thank you and goodbye::English->Turkish: requested=40, accepted=41, current=81/300
greetings_and_basic_conversation::saying thank you and goodbye::English->Turkish: requested=40, accepted=40, current=121/300
greetings_and_basic_conversation::saying thank you and goodbye::English->Turkish: requested=40, accepted=38, current=159/300
greetings_and_basic_conversation::saying thank you and goodbye::English->Turkish: requested=40, accepted=39, current=198/300
greetings_and_basic_conversation::saying thank you and goodbye::English->Turkish: requested=40, accepted=36, current=234/300
greetings_and_basic_conversation::saying thank you and goodbye::English->Turkish: requested=40, accepted=38, current=272/300
greetings_and_basic_conversation::saying thank you and goodbye::English->Turkish: requested=28, accepted=27, current=299/300
greetings_and_basic_conversation::saying thank you and goodbye::English->Turkish: requested=1, accepted=5, current=304/300

greetings_and_basic_conversation / saying thank you and goodbye / Turkish->English:   0%|          | 0/300 [00…

greetings_and_basic_conversation::saying thank you and goodbye::Turkish->English: requested=40, accepted=39, current=39/300
greetings_and_basic_conversation::saying thank you and goodbye::Turkish->English: requested=40, accepted=38, current=77/300
greetings_and_basic_conversation::saying thank you and goodbye::Turkish->English: requested=40, accepted=37, current=114/300
greetings_and_basic_conversation::saying thank you and goodbye::Turkish->English: requested=40, accepted=38, current=152/300
greetings_and_basic_conversation::saying thank you and goodbye::Turkish->English: requested=40, accepted=39, current=191/300
greetings_and_basic_conversation::saying thank you and goodbye::Turkish->English: requested=40, accepted=38, current=229/300
greetings_and_basic_conversation::saying thank you and goodbye::Turkish->English: requested=40, accepted=40, current=269/300
greetings_and_basic_conversation::saying thank you and goodbye::Turkish->English: requested=31, accepted=30, current=299/300
greetings_and_basic_conversation::saying thank you and goodbye::Turkish->English: requested=1, accepted=4, current=303/300

greetings_and_basic_conversation / asking someone to repeat slowly / English->Turkish:   0%|          | 0/300 …

greetings_and_basic_conversation::asking someone to repeat slowly::English->Turkish: requested=40, accepted=40, current=40/300
greetings_and_basic_conversation::asking someone to repeat slowly::English->Turkish: requested=40, accepted=50, current=90/300
greetings_and_basic_conversation::asking someone to repeat slowly::English->Turkish: requested=40, accepted=40, current=130/300
greetings_and_basic_conversation::asking someone to repeat slowly::English->Turkish: requested=40, accepted=39, current=169/300
greetings_and_basic_conversation::asking someone to repeat slowly::English->Turkish: requested=40, accepted=38, current=207/300
greetings_and_basic_conversation::asking someone to repeat slowly::English->Turkish: requested=40, accepted=38, current=245/300
greetings_and_basic_conversation::asking someone to repeat slowly::English->Turkish: requested=40, accepted=38, current=283/300
greetings_and_basic_conversation::asking someone to repeat slowly::English->Turkish: requested=17, accepted=17, current=300/300

greetings_and_basic_conversation / asking someone to repeat slowly / Turkish->English:   0%|          | 0/300 …

greetings_and_basic_conversation::asking someone to repeat slowly::Turkish->English: requested=40, accepted=40, current=40/300
greetings_and_basic_conversation::asking someone to repeat slowly::Turkish->English: requested=40, accepted=42, current=82/300
greetings_and_basic_conversation::asking someone to repeat slowly::Turkish->English: requested=40, accepted=42, current=124/300
greetings_and_basic_conversation::asking someone to repeat slowly::Turkish->English: requested=40, accepted=51, current=175/300
greetings_and_basic_conversation::asking someone to repeat slowly::Turkish->English: requested=40, accepted=41, current=216/300
greetings_and_basic_conversation::asking someone to repeat slowly::Turkish->English: requested=40, accepted=45, current=261/300
greetings_and_basic_conversation::asking someone to repeat slowly::Turkish->English: requested=39, accepted=36, current=297/300
greetings_and_basic_conversation::asking someone to repeat slowly::Turkish->English: requested=3, accepted=3, current=300/300

greetings_and_basic_conversation / simple misunderstanding phrases / English->Turkish:   0%|          | 0/300 …

greetings_and_basic_conversation::simple misunderstanding phrases::English->Turkish: requested=40, accepted=40, current=40/300
greetings_and_basic_conversation::simple misunderstanding phrases::English->Turkish: requested=40, accepted=39, current=79/300
greetings_and_basic_conversation::simple misunderstanding phrases::English->Turkish: requested=40, accepted=42, current=121/300
greetings_and_basic_conversation::simple misunderstanding phrases::English->Turkish: requested=40, accepted=39, current=160/300
greetings_and_basic_conversation::simple misunderstanding phrases::English->Turkish: requested=40, accepted=39, current=199/300
greetings_and_basic_conversation::simple misunderstanding phrases::English->Turkish: requested=40, accepted=40, current=239/300
greetings_and_basic_conversation::simple misunderstanding phrases::English->Turkish: requested=40, accepted=42, current=281/300
greetings_and_basic_conversation::simple misunderstanding phrases::English->Turkish: requested=19, accepted=19, current=300/300

greetings_and_basic_conversation / simple misunderstanding phrases / Turkish->English:   0%|          | 0/300 …

greetings_and_basic_conversation::simple misunderstanding phrases::Turkish->English: requested=40, accepted=41, current=41/300
greetings_and_basic_conversation::simple misunderstanding phrases::Turkish->English: requested=40, accepted=41, current=82/300
greetings_and_basic_conversation::simple misunderstanding phrases::Turkish->English: requested=40, accepted=40, current=122/300
greetings_and_basic_conversation::simple misunderstanding phrases::Turkish->English: requested=40, accepted=42, current=164/300
greetings_and_basic_conversation::simple misunderstanding phrases::Turkish->English: requested=40, accepted=41, current=205/300
greetings_and_basic_conversation::simple misunderstanding phrases::Turkish->English: requested=40, accepted=38, current=243/300
greetings_and_basic_conversation::simple misunderstanding phrases::Turkish->English: requested=40, accepted=39, current=282/300
greetings_and_basic_conversation::simple misunderstanding phrases::Turkish->English: requested=18, accepted=18, current=300/300

seat_and_cabin_location / finding assigned seat / English->Turkish:   0%|          | 0/666 [00:00<?, ?it/s]

seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=41, current=41/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=41, current=82/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=43, current=125/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=37, current=162/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=41, current=203/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=41, current=244/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=39, current=283/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=42, current=325/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=40, current=365/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=40, current=405/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=40, current=445/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=41, current=486/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=41, current=527/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=42, current=569/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=39, current=608/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=40, accepted=40, current=648/666
seat_and_cabin_location::finding assigned seat::English->Turkish: requested=18, accepted=18, current=666/666

seat_and_cabin_location / finding assigned seat / Turkish->English:   0%|          | 0/666 [00:00<?, ?it/s]

seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=43, current=43/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=42, current=85/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=38, current=123/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=41, current=164/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=38, current=202/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=39, current=241/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=43, current=284/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=49, current=333/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=42, current=375/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=46, current=421/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=50, current=471/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=38, current=509/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=42, current=551/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=39, current=590/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=40, accepted=40, current=630/666
seat_and_cabin_location::finding assigned seat::Turkish->English: requested=36, accepted=38, current=668/666

seat_and_cabin_location / someone sitting in passenger seat / English->Turkish:   0%|          | 0/666 [00:00<…

seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=41, current=41/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=45, current=86/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=46, current=132/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=39, current=171/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=38, current=209/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=39, current=248/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=39, current=287/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=41, current=328/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=39, current=367/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=39, current=406/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=40, current=446/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=40, current=486/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=40, current=526/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=43, current=569/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=40, current=609/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=40, accepted=39, current=648/666
seat_and_cabin_location::someone sitting in passenger seat::English->Turkish: requested=18, accepted=18, current=666/666

seat_and_cabin_location / someone sitting in passenger seat / Turkish->English:   0%|          | 0/666 [00:00<…

seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=39, current=39/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=44, current=83/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=43, current=126/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=39, current=165/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=42, current=207/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=39, current=246/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=44, current=290/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=39, current=329/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=44, current=373/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=42, current=415/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=40, current=455/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=43, current=498/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=41, current=539/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=39, current=578/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=41, current=619/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=40, accepted=39, current=658/666
seat_and_cabin_location::someone sitting in passenger seat::Turkish->English: requested=8, accepted=8, current=666/666

seat_and_cabin_location / window aisle and middle seat requests / English->Turkish:   0%|          | 0/666 [00…

seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=43, current=43/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=41, current=84/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=41, current=125/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=43, current=168/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=41, current=209/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=46, current=255/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=38, current=293/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=40, current=333/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=46, current=379/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=42, current=421/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=42, current=463/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=39, current=502/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=42, current=544/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=40, current=584/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=40, accepted=48, current=632/666
seat_and_cabin_location::window aisle and middle seat requests::English->Turkish: requested=34, accepted=34, current=666/666

seat_and_cabin_location / window aisle and middle seat requests / Turkish->English:   0%|          | 0/666 [00…

seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=43, current=43/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=40, current=83/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=48, current=131/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=42, current=173/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=41, current=214/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=41, current=255/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=40, current=295/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=45, current=340/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=47, current=387/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=44, current=431/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=40, current=471/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=42, current=513/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=41, current=554/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=44, current=598/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=40, accepted=42, current=640/666
seat_and_cabin_location::window aisle and middle seat requests::Turkish->English: requested=26, accepted=26, current=666/666

seat_and_cabin_location / family sitting together / English->Turkish:   0%|          | 0/666 [00:00<?, ?it/s]

seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=41, current=41/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=38, current=79/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=41, current=120/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=36, current=156/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=39, current=195/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=40, current=235/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=39, current=274/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=43, current=317/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=40, current=357/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=43, current=400/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=41, current=441/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=39, current=480/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=42, current=522/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=42, current=564/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=40, current=604/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=40, accepted=42, current=646/666
seat_and_cabin_location::family sitting together::English->Turkish: requested=20, accepted=20, current=666/666

seat_and_cabin_location / family sitting together / Turkish->English:   0%|          | 0/666 [00:00<?, ?it/s]

seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=40, current=40/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=42, current=82/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=40, current=122/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=38, current=160/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=41, current=201/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=45, current=246/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=40, current=286/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=44, current=330/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=39, current=369/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=40, current=409/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=42, current=451/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=40, current=491/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=38, current=529/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=39, current=568/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=43, current=611/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=40, accepted=41, current=652/666
seat_and_cabin_location::family sitting together::Turkish->English: requested=14, accepted=14, current=666/666

seat_and_cabin_location / overhead bin and under-seat bag placement / English->Turkish:   0%|          | 0/666…

seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=42, current=42/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=43, current=85/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=41, current=126/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=43, current=169/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=45, current=214/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=40, current=254/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=45, current=299/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=43, current=342/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=45, current=387/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=39, current=426/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=44, current=470/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=43, current=513/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=42, current=555/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=44, current=599/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=40, accepted=41, current=640/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=26, accepted=25, current=665/666
seat_and_cabin_location::overhead bin and under-seat bag placement::English->Turkish: requested=1, accepted=1, current=666/666

seat_and_cabin_location / overhead bin and under-seat bag placement / Turkish->English:   0%|          | 0/666…

seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=39, current=39/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=40, current=79/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=46, current=125/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=41, current=166/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=43, current=209/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=38, current=247/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=40, current=287/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=42, current=329/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=43, current=372/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=44, current=416/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=40, current=456/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=41, current=497/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=39, current=536/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=38, current=574/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=42, current=616/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=40, accepted=44, current=660/666
seat_and_cabin_location::overhead bin and under-seat bag placement::Turkish->English: requested=6, accepted=6, current=666/666

seat_and_cabin_location / seatbelt and aisle clearance instructions / English->Turkish:   0%|          | 0/666…

seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=40, current=40/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=37, current=77/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=40, current=117/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=39, current=156/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=42, current=198/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=41, current=239/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=41, current=280/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=38, current=318/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=39, current=357/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=40, current=397/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=44, current=441/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=39, current=480/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=41, current=521/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=38, current=559/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=44, current=603/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=40, accepted=42, current=645/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=21, accepted=20, current=665/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::English->Turkish: requested=1, accepted=5, current=670/666

seat_and_cabin_location / seatbelt and aisle clearance instructions / Turkish->English:   0%|          | 0/666…

seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=40, current=40/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=41, current=81/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=37, current=118/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=42, current=160/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=41, current=201/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=44, current=245/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=43, current=288/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=42, current=330/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=50, current=380/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=40, current=420/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=39, current=459/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=37, current=496/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=44, current=540/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=41, current=581/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=41, current=622/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=40, accepted=40, current=662/666
seat_and_cabin_location::seatbelt and aisle clearance instructions::Turkish->English: requested=4, accepted=4, current=666/666

toilet_and_lavatory / asking where the toilet is / English->Turkish:   0%|          | 0/416 [00:00<?, ?it/s]

toilet_and_lavatory::asking where the toilet is::English->Turkish: requested=40, accepted=39, current=39/416
toilet_and_lavatory::asking where the toilet is::English->Turkish: requested=40, accepted=38, current=77/416
toilet_and_lavatory::asking where the toilet is::English->Turkish: requested=40, accepted=40, current=117/416
toilet_and_lavatory::asking where the toilet is::English->Turkish: requested=40, accepted=41, current=158/416
toilet_and_lavatory::asking where the toilet is::English->Turkish: requested=40, accepted=45, current=203/416
toilet_and_lavatory::asking where the toilet is::English->Turkish: requested=40, accepted=45, current=248/416
toilet_and_lavatory::asking where the toilet is::English->Turkish: requested=40, accepted=60, current=308/416
toilet_and_lavatory::asking where the toilet is::English->Turkish: requested=40, accepted=39, current=347/416
toilet_and_lavatory::asking where the toilet is::English->Turkish: requested=40, accepted=44, current=391/416
toilet_and_lavatory::asking where the toilet is::English->Turkish: requested=25, accepted=24, current=415/416
toilet_and_lavatory::asking where the toilet is::English->Turkish: requested=1, accepted=3, current=418/416

toilet_and_lavatory / asking where the toilet is / Turkish->English:   0%|          | 0/416 [00:00<?, ?it/s]

toilet_and_lavatory::asking where the toilet is::Turkish->English: requested=40, accepted=38, current=38/416
toilet_and_lavatory::asking where the toilet is::Turkish->English: requested=40, accepted=43, current=81/416
toilet_and_lavatory::asking where the toilet is::Turkish->English: requested=40, accepted=37, current=118/416
toilet_and_lavatory::asking where the toilet is::Turkish->English: requested=40, accepted=38, current=156/416
toilet_and_lavatory::asking where the toilet is::Turkish->English: requested=40, accepted=50, current=206/416
toilet_and_lavatory::asking where the toilet is::Turkish->English: requested=40, accepted=39, current=245/416
toilet_and_lavatory::asking where the toilet is::Turkish->English: requested=40, accepted=41, current=286/416
toilet_and_lavatory::asking where the toilet is::Turkish->English: requested=40, accepted=40, current=326/416
toilet_and_lavatory::asking where the toilet is::Turkish->English: requested=40, accepted=38, current=364/416
toilet_and_lavatory::asking where the toilet is::Turkish->English: requested=40, accepted=39, current=403/416
toilet_and_lavatory::asking where the toilet is::Turkish->English: requested=13, accepted=13, current=416/416

toilet_and_lavatory / asking permission to use the toilet / English->Turkish:   0%|          | 0/416 [00:00<?,…

toilet_and_lavatory::asking permission to use the toilet::English->Turkish: requested=40, accepted=46, current=46/416
toilet_and_lavatory::asking permission to use the toilet::English->Turkish: requested=40, accepted=39, current=85/416
toilet_and_lavatory::asking permission to use the toilet::English->Turkish: requested=40, accepted=39, current=124/416
toilet_and_lavatory::asking permission to use the toilet::English->Turkish: requested=40, accepted=46, current=170/416
toilet_and_lavatory::asking permission to use the toilet::English->Turkish: requested=40, accepted=52, current=222/416
toilet_and_lavatory::asking permission to use the toilet::English->Turkish: requested=40, accepted=42, current=264/416
toilet_and_lavatory::asking permission to use the toilet::English->Turkish: requested=40, accepted=38, current=302/416
toilet_and_lavatory::asking permission to use the toilet::English->Turkish: requested=40, accepted=40, current=342/416
toilet_and_lavatory::asking permission to use the toilet::English->Turkish: requested=40, accepted=40, current=382/416
toilet_and_lavatory::asking permission to use the toilet::English->Turkish: requested=34, accepted=36, current=418/416

toilet_and_lavatory / asking permission to use the toilet / Turkish->English:   0%|          | 0/416 [00:00<?,…

toilet_and_lavatory::asking permission to use the toilet::Turkish->English: requested=40, accepted=40, current=40/416
toilet_and_lavatory::asking permission to use the toilet::Turkish->English: requested=40, accepted=40, current=80/416
toilet_and_lavatory::asking permission to use the toilet::Turkish->English: requested=40, accepted=49, current=129/416
toilet_and_lavatory::asking permission to use the toilet::Turkish->English: requested=40, accepted=40, current=169/416
toilet_and_lavatory::asking permission to use the toilet::Turkish->English: requested=40, accepted=50, current=219/416
toilet_and_lavatory::asking permission to use the toilet::Turkish->English: requested=40, accepted=38, current=257/416
toilet_and_lavatory::asking permission to use the toilet::Turkish->English: requested=40, accepted=40, current=297/416
toilet_and_lavatory::asking permission to use the toilet::Turkish->English: requested=40, accepted=48, current=345/416
toilet_and_lavatory::asking permission to use the toilet::Turkish->English: requested=40, accepted=50, current=395/416
toilet_and_lavatory::asking permission to use the toilet::Turkish->English: requested=21, accepted=21, current=416/416

toilet_and_lavatory / toilet occupied or unavailable / English->Turkish:   0%|          | 0/416 [00:00<?, ?it/…

toilet_and_lavatory::toilet occupied or unavailable::English->Turkish: requested=40, accepted=40, current=40/416
toilet_and_lavatory::toilet occupied or unavailable::English->Turkish: requested=40, accepted=40, current=80/416
toilet_and_lavatory::toilet occupied or unavailable::English->Turkish: requested=40, accepted=40, current=120/416
toilet_and_lavatory::toilet occupied or unavailable::English->Turkish: requested=40, accepted=41, current=161/416
toilet_and_lavatory::toilet occupied or unavailable::English->Turkish: requested=40, accepted=38, current=199/416
toilet_and_lavatory::toilet occupied or unavailable::English->Turkish: requested=40, accepted=38, current=237/416
toilet_and_lavatory::toilet occupied or unavailable::English->Turkish: requested=40, accepted=41, current=278/416
toilet_and_lavatory::toilet occupied or unavailable::English->Turkish: requested=40, accepted=41, current=319/416
toilet_and_lavatory::toilet occupied or unavailable::English->Turkish: requested=40, accepted=39, current=358/416
toilet_and_lavatory::toilet occupied or unavailable::English->Turkish: requested=40, accepted=40, current=398/416
toilet_and_lavatory::toilet occupied or unavailable::English->Turkish: requested=18, accepted=18, current=416/416

toilet_and_lavatory / toilet occupied or unavailable / Turkish->English:   0%|          | 0/416 [00:00<?, ?it/…

toilet_and_lavatory::toilet occupied or unavailable::Turkish->English: requested=40, accepted=42, current=42/416
toilet_and_lavatory::toilet occupied or unavailable::Turkish->English: requested=40, accepted=40, current=82/416
toilet_and_lavatory::toilet occupied or unavailable::Turkish->English: requested=40, accepted=42, current=124/416
toilet_and_lavatory::toilet occupied or unavailable::Turkish->English: requested=40, accepted=39, current=163/416
toilet_and_lavatory::toilet occupied or unavailable::Turkish->English: requested=40, accepted=43, current=206/416
toilet_and_lavatory::toilet occupied or unavailable::Turkish->English: requested=40, accepted=40, current=246/416
toilet_and_lavatory::toilet occupied or unavailable::Turkish->English: requested=40, accepted=41, current=287/416
toilet_and_lavatory::toilet occupied or unavailable::Turkish->English: requested=40, accepted=45, current=332/416
toilet_and_lavatory::toilet occupied or unavailable::Turkish->English: requested=40, accepted=40, current=372/416
toilet_and_lavatory::toilet occupied or unavailable::Turkish->English: requested=40, accepted=39, current=411/416
toilet_and_lavatory::toilet occupied or unavailable::Turkish->English: requested=5, accepted=5, current=416/416

toilet_and_lavatory / toilet problem reporting / English->Turkish:   0%|          | 0/416 [00:00<?, ?it/s]

toilet_and_lavatory::toilet problem reporting::English->Turkish: requested=40, accepted=40, current=40/416
toilet_and_lavatory::toilet problem reporting::English->Turkish: requested=40, accepted=44, current=84/416
toilet_and_lavatory::toilet problem reporting::English->Turkish: requested=40, accepted=39, current=123/416
toilet_and_lavatory::toilet problem reporting::English->Turkish: requested=40, accepted=39, current=162/416
toilet_and_lavatory::toilet problem reporting::English->Turkish: requested=40, accepted=36, current=198/416
toilet_and_lavatory::toilet problem reporting::English->Turkish: requested=40, accepted=41, current=239/416
toilet_and_lavatory::toilet problem reporting::English->Turkish: requested=40, accepted=41, current=280/416
toilet_and_lavatory::toilet problem reporting::English->Turkish: requested=40, accepted=41, current=321/416
toilet_and_lavatory::toilet problem reporting::English->Turkish: requested=40, accepted=37, current=358/416
toilet_and_lavatory::toilet problem reporting::English->Turkish: requested=40, accepted=41, current=399/416
toilet_and_lavatory::toilet problem reporting::English->Turkish: requested=17, accepted=17, current=416/416

toilet_and_lavatory / toilet problem reporting / Turkish->English:   0%|          | 0/416 [00:00<?, ?it/s]

toilet_and_lavatory::toilet problem reporting::Turkish->English: requested=40, accepted=42, current=42/416
toilet_and_lavatory::toilet problem reporting::Turkish->English: requested=40, accepted=45, current=87/416
toilet_and_lavatory::toilet problem reporting::Turkish->English: requested=40, accepted=38, current=125/416
toilet_and_lavatory::toilet problem reporting::Turkish->English: requested=40, accepted=45, current=170/416
toilet_and_lavatory::toilet problem reporting::Turkish->English: requested=40, accepted=39, current=209/416
toilet_and_lavatory::toilet problem reporting::Turkish->English: requested=40, accepted=43, current=252/416
toilet_and_lavatory::toilet problem reporting::Turkish->English: requested=40, accepted=42, current=294/416
toilet_and_lavatory::toilet problem reporting::Turkish->English: requested=40, accepted=40, current=334/416
toilet_and_lavatory::toilet problem reporting::Turkish->English: requested=40, accepted=41, current=375/416
toilet_and_lavatory::toilet problem reporting::Turkish->English: requested=40, accepted=40, current=415/416
toilet_and_lavatory::toilet problem reporting::Turkish->English: requested=1, accepted=1, current=416/416

toilet_and_lavatory / seatbelt sign and toilet restriction / English->Turkish:   0%|          | 0/416 [00:00<?…

toilet_and_lavatory::seatbelt sign and toilet restriction::English->Turkish: requested=40, accepted=42, current=42/416
toilet_and_lavatory::seatbelt sign and toilet restriction::English->Turkish: requested=40, accepted=42, current=84/416
toilet_and_lavatory::seatbelt sign and toilet restriction::English->Turkish: requested=40, accepted=40, current=124/416
toilet_and_lavatory::seatbelt sign and toilet restriction::English->Turkish: requested=40, accepted=41, current=165/416
toilet_and_lavatory::seatbelt sign and toilet restriction::English->Turkish: requested=40, accepted=40, current=205/416
toilet_and_lavatory::seatbelt sign and toilet restriction::English->Turkish: requested=40, accepted=39, current=244/416
toilet_and_lavatory::seatbelt sign and toilet restriction::English->Turkish: requested=40, accepted=37, current=281/416
toilet_and_lavatory::seatbelt sign and toilet restriction::English->Turkish: requested=40, accepted=40, current=321/416
toilet_and_lavatory::seatbelt sign and toilet restriction::English->Turkish: requested=40, accepted=37, current=358/416
toilet_and_lavatory::seatbelt sign and toilet restriction::English->Turkish: requested=40, accepted=38, current=396/416
toilet_and_lavatory::seatbelt sign and toilet restriction::English->Turkish: requested=20, accepted=20, current=416/416

toilet_and_lavatory / seatbelt sign and toilet restriction / Turkish->English:   0%|          | 0/416 [00:00<?…

toilet_and_lavatory::seatbelt sign and toilet restriction::Turkish->English: requested=40, accepted=39, current=39/416
toilet_and_lavatory::seatbelt sign and toilet restriction::Turkish->English: requested=40, accepted=43, current=82/416
toilet_and_lavatory::seatbelt sign and toilet restriction::Turkish->English: requested=40, accepted=44, current=126/416
toilet_and_lavatory::seatbelt sign and toilet restriction::Turkish->English: requested=40, accepted=42, current=168/416
toilet_and_lavatory::seatbelt sign and toilet restriction::Turkish->English: requested=40, accepted=41, current=209/416
toilet_and_lavatory::seatbelt sign and toilet restriction::Turkish->English: requested=40, accepted=44, current=253/416
toilet_and_lavatory::seatbelt sign and toilet restriction::Turkish->English: requested=40, accepted=44, current=297/416
toilet_and_lavatory::seatbelt sign and toilet restriction::Turkish->English: requested=40, accepted=40, current=337/416
toilet_and_lavatory::seatbelt sign and toilet restriction::Turkish->English: requested=40, accepted=40, current=377/416
toilet_and_lavatory::seatbelt sign and toilet restriction::Turkish->English: requested=39, accepted=37, current=414/416
toilet_and_lavatory::seatbelt sign and toilet restriction::Turkish->English: requested=2, accepted=2, current=416/416

toilet_and_lavatory / urgent toilet need / English->Turkish:   0%|          | 0/416 [00:00<?, ?it/s]

toilet_and_lavatory::urgent toilet need::English->Turkish: requested=40, accepted=50, current=50/416
toilet_and_lavatory::urgent toilet need::English->Turkish: requested=40, accepted=40, current=90/416
toilet_and_lavatory::urgent toilet need::English->Turkish: requested=40, accepted=42, current=132/416
toilet_and_lavatory::urgent toilet need::English->Turkish: requested=40, accepted=40, current=172/416
toilet_and_lavatory::urgent toilet need::English->Turkish: requested=40, accepted=40, current=212/416
toilet_and_lavatory::urgent toilet need::English->Turkish: requested=40, accepted=38, current=250/416
toilet_and_lavatory::urgent toilet need::English->Turkish: requested=40, accepted=38, current=288/416
toilet_and_lavatory::urgent toilet need::English->Turkish: requested=40, accepted=42, current=330/416
toilet_and_lavatory::urgent toilet need::English->Turkish: requested=40, accepted=41, current=371/416
toilet_and_lavatory::urgent toilet need::English->Turkish: requested=40, accepted=41, current=412/416
toilet_and_lavatory::urgent toilet need::English->Turkish: requested=4, accepted=4, current=416/416

toilet_and_lavatory / urgent toilet need / Turkish->English:   0%|          | 0/416 [00:00<?, ?it/s]

toilet_and_lavatory::urgent toilet need::Turkish->English: requested=40, accepted=40, current=40/416
toilet_and_lavatory::urgent toilet need::Turkish->English: requested=40, accepted=46, current=86/416
toilet_and_lavatory::urgent toilet need::Turkish->English: requested=40, accepted=43, current=129/416
toilet_and_lavatory::urgent toilet need::Turkish->English: requested=40, accepted=44, current=173/416
toilet_and_lavatory::urgent toilet need::Turkish->English: requested=40, accepted=42, current=215/416
toilet_and_lavatory::urgent toilet need::Turkish->English: requested=40, accepted=42, current=257/416
toilet_and_lavatory::urgent toilet need::Turkish->English: requested=40, accepted=41, current=298/416
toilet_and_lavatory::urgent toilet need::Turkish->English: requested=40, accepted=44, current=342/416
toilet_and_lavatory::urgent toilet need::Turkish->English: requested=40, accepted=41, current=383/416
toilet_and_lavatory::urgent toilet need::Turkish->English: requested=33, accepted=34, current=417/416

food_and_drink / asking for water tea coffee or juice / English->Turkish:   0%|          | 0/642 [00:00<?, ?it…

food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=40, current=40/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=38, current=78/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=39, current=117/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=50, current=167/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=41, current=208/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=37, current=245/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=37, current=282/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=44, current=326/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=42, current=368/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=41, current=409/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=41, current=450/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=37, current=487/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=42, current=529/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=38, current=567/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=40, accepted=40, current=607/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=35, accepted=33, current=640/642
food_and_drink::asking for water tea coffee or juice::English->Turkish: requested=2, accepted=2, current=642/642

food_and_drink / asking for water tea coffee or juice / Turkish->English:   0%|          | 0/642 [00:00<?, ?it…

food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=38, current=38/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=41, current=79/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=40, current=119/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=44, current=163/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=39, current=202/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=37, current=239/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=37, current=276/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=40, current=316/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=40, current=356/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=38, current=394/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=37, current=431/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=41, current=472/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=39, current=511/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=42, current=553/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=38, current=591/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=40, accepted=37, current=628/642
food_and_drink::asking for water tea coffee or juice::Turkish->English: requested=14, accepted=14, current=642/642

food_and_drink / meal choice chicken beef fish pasta / English->Turkish:   0%|          | 0/642 [00:00<?, ?it/…

food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=39, current=39/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=39, current=78/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=37, current=115/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=42, current=157/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=45, current=202/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=38, current=240/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=38, current=278/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=39, current=317/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=41, current=358/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=38, current=396/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=37, current=433/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=43, current=476/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=41, current=517/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=38, current=555/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=40, current=595/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=40, accepted=41, current=636/642
food_and_drink::meal choice chicken beef fish pasta::English->Turkish: requested=6, accepted=6, current=642/642

food_and_drink / meal choice chicken beef fish pasta / Turkish->English:   0%|          | 0/642 [00:00<?, ?it/…

food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=40, current=40/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=39, current=79/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=40, current=119/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=42, current=161/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=43, current=204/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=39, current=243/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=39, current=282/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=50, current=332/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=38, current=370/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=40, current=410/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=40, current=450/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=41, current=491/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=37, current=528/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=50, current=578/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=40, accepted=39, current=617/642
food_and_drink::meal choice chicken beef fish pasta::Turkish->English: requested=25, accepted=25, current=642/642

food_and_drink / vegetarian vegan halal and dietary requests / English->Turkish:   0%|          | 0/642 [00:00…

food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=39, current=39/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=39, current=78/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=38, current=116/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=43, current=159/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=40, current=199/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=39, current=238/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=40, current=278/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=37, current=315/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=42, current=357/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=39, current=396/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=36, current=432/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=40, current=472/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=41, current=513/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=42, current=555/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=40, current=595/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=40, accepted=39, current=634/642
food_and_drink::vegetarian vegan halal and dietary requests::English->Turkish: requested=8, accepted=8, current=642/642

food_and_drink / vegetarian vegan halal and dietary requests / Turkish->English:   0%|          | 0/642 [00:00…

food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=45, current=45/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=40, current=85/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=42, current=127/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=40, current=167/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=38, current=205/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=42, current=247/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=42, current=289/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=45, current=334/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=42, current=376/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=39, current=415/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=39, current=454/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=39, current=493/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=37, current=530/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=44, current=574/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=40, accepted=50, current=624/642
food_and_drink::vegetarian vegan halal and dietary requests::Turkish->English: requested=18, accepted=18, current=642/642

food_and_drink / food allergy warnings / English->Turkish:   0%|          | 0/642 [00:00<?, ?it/s]

food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=40, current=40/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=38, current=78/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=37, current=115/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=40, current=155/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=38, current=193/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=37, current=230/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=39, current=269/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=37, current=306/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=38, current=344/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=39, current=383/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=39, current=422/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=44, current=466/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=38, current=504/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=38, current=542/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=40, current=582/642
food_and_drink::food allergy warnings::English->Turkish: requested=40, accepted=38, current=620/642
food_and_drink::food allergy warnings::English->Turkish: requested=22, accepted=22, current=642/642

food_and_drink / food allergy warnings / Turkish->English:   0%|          | 0/642 [00:00<?, ?it/s]

food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=41, current=41/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=38, current=79/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=38, current=117/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=40, current=157/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=42, current=199/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=43, current=242/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=50, current=292/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=40, current=332/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=41, current=373/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=41, current=414/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=39, current=453/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=44, current=497/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=42, current=539/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=38, current=577/642
food_and_drink::food allergy warnings::Turkish->English: requested=40, accepted=48, current=625/642
food_and_drink::food allergy warnings::Turkish->English: requested=17, accepted=17, current=642/642

food_and_drink / asking for bread napkin or extra drink / English->Turkish:   0%|          | 0/642 [00:00<?, ?…

food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=42, current=42/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=42, current=84/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=42, current=126/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=43, current=169/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=39, current=208/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=41, current=249/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=39, current=288/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=40, current=328/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=41, current=369/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=46, current=415/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=44, current=459/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=40, current=499/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=43, current=542/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=40, current=582/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=40, accepted=41, current=623/642
food_and_drink::asking for bread napkin or extra drink::English->Turkish: requested=19, accepted=19, current=642/642

food_and_drink / asking for bread napkin or extra drink / Turkish->English:   0%|          | 0/642 [00:00<?, ?…

food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=42, current=42/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=41, current=83/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=41, current=124/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=45, current=169/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=44, current=213/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=41, current=254/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=42, current=296/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=44, current=340/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=45, current=385/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=42, current=427/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=49, current=476/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=40, current=516/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=48, current=564/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=40, accepted=44, current=608/642
food_and_drink::asking for bread napkin or extra drink::Turkish->English: requested=34, accepted=41, current=649/642

food_and_drink / complaining about cold or missing food / English->Turkish:   0%|          | 0/642 [00:00<?, ?…

food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=40, current=40/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=40, current=80/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=39, current=119/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=43, current=162/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=38, current=200/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=38, current=238/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=44, current=282/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=38, current=320/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=42, current=362/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=40, current=402/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=42, current=444/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=41, current=485/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=39, current=524/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=41, current=565/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=40, accepted=41, current=606/642
food_and_drink::complaining about cold or missing food::English->Turkish: requested=36, accepted=36, current=642/642

food_and_drink / complaining about cold or missing food / Turkish->English:   0%|          | 0/642 [00:00<?, ?…

food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=42, current=42/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=41, current=83/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=41, current=124/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=39, current=163/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=39, current=202/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=41, current=243/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=42, current=285/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=44, current=329/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=39, current=368/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=41, current=409/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=40, current=449/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=39, current=488/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=40, current=528/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=41, current=569/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=40, accepted=47, current=616/642
food_and_drink::complaining about cold or missing food::Turkish->English: requested=26, accepted=26, current=642/642

food_and_drink / special meal already ordered / English->Turkish:   0%|          | 0/642 [00:00<?, ?it/s]

food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=37, current=37/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=37, current=74/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=38, current=112/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=40, current=152/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=39, current=191/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=38, current=229/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=38, current=267/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=37, current=304/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=41, current=345/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=41, current=386/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=43, current=429/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=38, current=467/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=42, current=509/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=40, current=549/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=37, current=586/642
food_and_drink::special meal already ordered::English->Turkish: requested=40, accepted=37, current=623/642
food_and_drink::special meal already ordered::English->Turkish: requested=19, accepted=19, current=642/642

food_and_drink / special meal already ordered / Turkish->English:   0%|          | 0/642 [00:00<?, ?it/s]

food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=44, current=44/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=41, current=85/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=39, current=124/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=41, current=165/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=40, current=205/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=41, current=246/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=41, current=287/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=38, current=325/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=38, current=363/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=41, current=404/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=40, current=444/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=43, current=487/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=42, current=529/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=39, current=568/642
food_and_drink::special meal already ordered::Turkish->English: requested=40, accepted=41, current=609/642
food_and_drink::special meal already ordered::Turkish->English: requested=33, accepted=33, current=642/642

comfort_and_cabin_needs / asking for blanket or pillow / English->Turkish:   0%|          | 0/583 [00:00<?, ?i…

comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=40, accepted=38, current=38/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=40, accepted=39, current=77/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=40, accepted=42, current=119/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=40, accepted=40, current=159/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=40, accepted=50, current=209/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=40, accepted=38, current=247/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=40, accepted=40, current=287/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=40, accepted=41, current=328/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=40, accepted=40, current=368/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=40, accepted=44, current=412/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=40, accepted=42, current=454/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=40, accepted=43, current=497/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=40, accepted=47, current=544/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=39, accepted=36, current=580/583
comfort_and_cabin_needs::asking for blanket or pillow::English->Turkish: requested=3, accepted=3, current=583/583

comfort_and_cabin_needs / asking for blanket or pillow / Turkish->English:   0%|          | 0/583 [00:00<?, ?i…

comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=40, current=40/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=38, current=78/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=42, current=120/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=47, current=167/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=40, current=207/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=39, current=246/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=41, current=287/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=37, current=324/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=39, current=363/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=39, current=402/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=41, current=443/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=38, current=481/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=42, current=523/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=40, accepted=39, current=562/583
comfort_and_cabin_needs::asking for blanket or pillow::Turkish->English: requested=21, accepted=21, current=583/583

comfort_and_cabin_needs / feeling cold or hot / English->Turkish:   0%|          | 0/583 [00:00<?, ?it/s]

comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=43, current=43/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=39, current=82/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=43, current=125/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=39, current=164/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=41, current=205/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=39, current=244/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=39, current=283/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=40, current=323/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=41, current=364/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=40, current=404/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=40, current=444/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=41, current=485/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=38, current=523/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=40, accepted=40, current=563/583
comfort_and_cabin_needs::feeling cold or hot::English->Turkish: requested=20, accepted=20, current=583/583

comfort_and_cabin_needs / feeling cold or hot / Turkish->English:   0%|          | 0/583 [00:00<?, ?it/s]

comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=42, current=42/583
comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=38, current=80/583
comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=41, current=121/583
comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=46, current=167/583
comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=38, current=205/583
comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=39, current=244/583
comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=39, current=283/583
comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=41, current=324/583
comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=41, current=365/583
comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=41, current=406/583
comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=44, current=450/583
comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=40, current=490/583
comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=43, current=533/583
comfort_and_cabin_needs::feeling cold or hot::Turkish->English: requested=40, accepted=51, current=584/583

comfort_and_cabin_needs / air vent reading light and tray table / English->Turkish:   0%|          | 0/583 [00…

comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=39, current=39/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=41, current=80/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=40, current=120/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=38, current=158/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=44, current=202/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=49, current=251/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=40, current=291/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=39, current=330/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=37, current=367/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=40, current=407/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=40, current=447/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=39, current=486/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=41, current=527/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=40, accepted=40, current=567/583
comfort_and_cabin_needs::air vent reading light and tray table::English->Turkish: requested=16, accepted=16, current=583/583

comfort_and_cabin_needs / air vent reading light and tray table / Turkish->English:   0%|          | 0/583 [00…

comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=41, current=41/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=46, current=87/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=41, current=128/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=39, current=167/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=39, current=206/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=45, current=251/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=39, current=290/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=43, current=333/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=43, current=376/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=36, current=412/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=39, current=451/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=38, current=489/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=40, current=529/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=40, accepted=38, current=567/583
comfort_and_cabin_needs::air vent reading light and tray table::Turkish->English: requested=16, accepted=16, current=583/583

comfort_and_cabin_needs / screen headphones and entertainment problems / English->Turkish:   0%|          | 0/…

comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=42, current=42/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=46, current=88/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=38, current=126/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=40, current=166/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=44, current=210/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=39, current=249/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=41, current=290/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=39, current=329/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=41, current=370/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=39, current=409/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=40, current=449/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=38, current=487/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=41, current=528/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=40, accepted=42, current=570/583
comfort_and_cabin_needs::screen headphones and entertainment problems::English->Turkish: requested=13, accepted=13, current=583/583

comfort_and_cabin_needs / screen headphones and entertainment problems / Turkish->English:   0%|          | 0/…

comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=38, current=38/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=41, current=79/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=37, current=116/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=49, current=165/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=43, current=208/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=38, current=246/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=40, current=286/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=40, current=326/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=43, current=369/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=45, current=414/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=42, current=456/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=37, current=493/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=42, current=535/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=40, accepted=39, current=574/583
comfort_and_cabin_needs::screen headphones and entertainment problems::Turkish->English: requested=9, accepted=9, current=583/583

comfort_and_cabin_needs / seat recline or broken seat / English->Turkish:   0%|          | 0/583 [00:00<?, ?it…

comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=38, current=38/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=39, current=77/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=39, current=116/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=43, current=159/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=37, current=196/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=39, current=235/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=39, current=274/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=44, current=318/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=42, current=360/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=44, current=404/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=40, current=444/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=41, current=485/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=39, current=524/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=40, accepted=40, current=564/583
comfort_and_cabin_needs::seat recline or broken seat::English->Turkish: requested=19, accepted=19, current=583/583

comfort_and_cabin_needs / seat recline or broken seat / Turkish->English:   0%|          | 0/583 [00:00<?, ?it…

comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=39, current=39/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=44, current=83/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=39, current=122/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=40, current=162/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=42, current=204/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=45, current=249/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=42, current=291/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=41, current=332/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=43, current=375/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=44, current=419/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=38, current=457/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=41, current=498/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=41, current=539/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=40, accepted=38, current=577/583
comfort_and_cabin_needs::seat recline or broken seat::Turkish->English: requested=6, accepted=6, current=583/583

comfort_and_cabin_needs / asking for sick bag / English->Turkish:   0%|          | 0/583 [00:00<?, ?it/s]

comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=36, current=36/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=40, current=76/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=39, current=115/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=41, current=156/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=43, current=199/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=39, current=238/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=38, current=276/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=40, current=316/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=40, current=356/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=41, current=397/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=45, current=442/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=40, current=482/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=43, current=525/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=40, accepted=40, current=565/583
comfort_and_cabin_needs::asking for sick bag::English->Turkish: requested=18, accepted=18, current=583/583

comfort_and_cabin_needs / asking for sick bag / Turkish->English:   0%|          | 0/583 [00:00<?, ?it/s]

comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=40, current=40/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=44, current=84/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=42, current=126/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=41, current=167/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=40, current=207/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=39, current=246/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=40, current=286/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=39, current=325/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=41, current=366/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=45, current=411/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=41, current=452/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=41, current=493/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=37, current=530/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=40, accepted=39, current=569/583
comfort_and_cabin_needs::asking for sick bag::Turkish->English: requested=14, accepted=14, current=583/583

flight_time_delay_and_arrival / asking flight duration / English->Turkish:   0%|          | 0/666 [00:00<?, ?i…

flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=39, current=39/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=38, current=77/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=39, current=116/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=39, current=155/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=42, current=197/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=38, current=235/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=43, current=278/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=42, current=320/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=41, current=361/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=42, current=403/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=50, current=453/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=40, current=493/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=41, current=534/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=39, current=573/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=39, current=612/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=40, accepted=41, current=653/666
flight_time_delay_and_arrival::asking flight duration::English->Turkish: requested=13, accepted=13, current=666/666

flight_time_delay_and_arrival / asking flight duration / Turkish->English:   0%|          | 0/666 [00:00<?, ?i…

flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=41, current=41/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=50, current=91/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=45, current=136/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=40, current=176/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=41, current=217/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=38, current=255/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=40, current=295/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=43, current=338/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=40, current=378/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=36, current=414/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=47, current=461/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=43, current=504/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=40, current=544/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=40, current=584/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=40, current=624/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=40, accepted=39, current=663/666
flight_time_delay_and_arrival::asking flight duration::Turkish->English: requested=3, accepted=3, current=666/666

flight_time_delay_and_arrival / asking arrival and landing time / English->Turkish:   0%|          | 0/666 [00…

flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=43, current=43/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=39, current=82/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=41, current=123/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=39, current=162/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=39, current=201/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=39, current=240/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=41, current=281/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=44, current=325/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=40, current=365/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=42, current=407/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=42, current=449/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=38, current=487/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=40, current=527/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=40, current=567/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=41, current=608/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=40, accepted=41, current=649/666
flight_time_delay_and_arrival::asking arrival and landing time::English->Turkish: requested=17, accepted=17, current=666/666

flight_time_delay_and_arrival / asking arrival and landing time / Turkish->English:   0%|          | 0/666 [00…

flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=45, current=45/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=40, current=85/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=39, current=124/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=41, current=165/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=41, current=206/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=42, current=248/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=39, current=287/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=41, current=328/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=49, current=377/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=37, current=414/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=39, current=453/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=41, current=494/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=41, current=535/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=39, current=574/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=50, current=624/666
flight_time_delay_and_arrival::asking arrival and landing time::Turkish->English: requested=40, accepted=43, current=667/666

flight_time_delay_and_arrival / delay and waiting explanations / English->Turkish:   0%|          | 0/666 [00:…

flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=40, current=40/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=40, current=80/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=39, current=119/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=41, current=160/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=41, current=201/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=40, current=241/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=40, current=281/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=38, current=319/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=39, current=358/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=37, current=395/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=39, current=434/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=40, current=474/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=39, current=513/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=38, current=551/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=43, current=594/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=40, accepted=41, current=635/666
flight_time_delay_and_arrival::delay and waiting explanations::English->Turkish: requested=31, accepted=31, current=666/666

flight_time_delay_and_arrival / delay and waiting explanations / Turkish->English:   0%|          | 0/666 [00:…

flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=38, current=38/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=37, current=75/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=39, current=114/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=41, current=155/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=38, current=193/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=37, current=230/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=38, current=268/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=43, current=311/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=39, current=350/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=38, current=388/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=39, current=427/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=42, current=469/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=43, current=512/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=39, current=551/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=37, current=588/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=38, current=626/666
flight_time_delay_and_arrival::delay and waiting explanations::Turkish->English: requested=40, accepted=41, current=667/666

flight_time_delay_and_arrival / connecting flight concerns / English->Turkish:   0%|          | 0/666 [00:00<?…

flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=37, current=37/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=41, current=78/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=38, current=116/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=42, current=158/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=38, current=196/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=38, current=234/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=44, current=278/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=39, current=317/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=41, current=358/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=39, current=397/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=42, current=439/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=40, current=479/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=43, current=522/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=40, current=562/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=41, current=603/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=40, accepted=42, current=645/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=21, accepted=20, current=665/666
flight_time_delay_and_arrival::connecting flight concerns::English->Turkish: requested=1, accepted=2, current=667/666

flight_time_delay_and_arrival / connecting flight concerns / Turkish->English:   0%|          | 0/666 [00:00<?…

flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=40, current=40/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=40, current=80/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=42, current=122/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=45, current=167/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=40, current=207/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=44, current=251/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=40, current=291/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=41, current=332/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=39, current=371/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=40, current=411/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=38, current=449/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=42, current=491/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=41, current=532/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=39, current=571/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=44, current=615/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=40, accepted=38, current=653/666
flight_time_delay_and_arrival::connecting flight concerns::Turkish->English: requested=13, accepted=13, current=666/666

flight_time_delay_and_arrival / local time at destination / English->Turkish:   0%|          | 0/666 [00:00<?,…

flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=46, current=46/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=40, current=86/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=39, current=125/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=38, current=163/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=42, current=205/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=41, current=246/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=40, current=286/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=44, current=330/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=41, current=371/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=41, current=412/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=41, current=453/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=37, current=490/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=42, current=532/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=39, current=571/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=44, current=615/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=40, accepted=40, current=655/666
flight_time_delay_and_arrival::local time at destination::English->Turkish: requested=11, accepted=11, current=666/666

flight_time_delay_and_arrival / local time at destination / Turkish->English:   0%|          | 0/666 [00:00<?,…

flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=38, current=38/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=37, current=75/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=40, current=115/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=40, current=155/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=40, current=195/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=39, current=234/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=40, current=274/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=40, current=314/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=39, current=353/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=38, current=391/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=39, current=430/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=39, current=469/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=43, current=512/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=40, current=552/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=50, current=602/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=40, accepted=42, current=644/666
flight_time_delay_and_arrival::local time at destination::Turkish->English: requested=22, accepted=22, current=666/666

flight_time_delay_and_arrival / gate and baggage claim after landing / English->Turkish:   0%|          | 0/66…

flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=40, current=40/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=39, current=79/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=44, current=123/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=42, current=165/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=43, current=208/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=39, current=247/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=38, current=285/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=43, current=328/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=43, current=371/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=40, current=411/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=41, current=452/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=44, current=496/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=43, current=539/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=40, current=579/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=37, current=616/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=40, accepted=41, current=657/666
flight_time_delay_and_arrival::gate and baggage claim after landing::English->Turkish: requested=9, accepted=9, current=666/666

flight_time_delay_and_arrival / gate and baggage claim after landing / Turkish->English:   0%|          | 0/66…

flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=41, current=41/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=44, current=85/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=42, current=127/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=39, current=166/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=43, current=209/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=48, current=257/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=40, current=297/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=43, current=340/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=44, current=384/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=41, current=425/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=42, current=467/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=46, current=513/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=42, current=555/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=39, current=594/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=40, accepted=39, current=633/666
flight_time_delay_and_arrival::gate and baggage claim after landing::Turkish->English: requested=33, accepted=33, current=666/666

baggage_and_personal_items / placing cabin bag / English->Turkish:   0%|          | 0/583 [00:00<?, ?it/s]

baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=42, current=42/583
baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=39, current=81/583
baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=39, current=120/583
baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=46, current=166/583
baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=42, current=208/583
baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=41, current=249/583
baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=42, current=291/583
baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=40, current=331/583
baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=41, current=372/583
baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=45, current=417/583
baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=41, current=458/583
baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=41, current=499/583
baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=42, current=541/583
baggage_and_personal_items::placing cabin bag::English->Turkish: requested=40, accepted=44, current=585/583

baggage_and_personal_items / placing cabin bag / Turkish->English:   0%|          | 0/583 [00:00<?, ?it/s]

baggage_and_personal_items::placing cabin bag::Turkish->English: requested=40, accepted=44, current=44/583
baggage_and_personal_items::placing cabin bag::Turkish->English: requested=40, accepted=44, current=88/583
baggage_and_personal_items::placing cabin bag::Turkish->English: requested=40, accepted=41, current=129/583
baggage_and_personal_items::placing cabin bag::Turkish->English: requested=40, accepted=39, current=168/583
baggage_and_personal_items::placing cabin bag::Turkish->English: requested=40, accepted=45, current=213/583
baggage_and_personal_items::placing cabin bag::Turkish->English: requested=40, accepted=43, current=256/583
baggage_and_personal_items::placing cabin bag::Turkish->English: requested=40, accepted=42, current=298/583
baggage_and_personal_items::placing cabin bag::Turkish->English: requested=40, accepted=37, current=335/583
baggage_and_personal_items::placing cabin bag::Turkish->English: requested=40, accepted=44, current=379/583
baggage_and_personal_items::placing cabin bag::Turkish->English: requested=40, accepted=40, current=419/583
baggage_and_personal_items::placing cabin bag::Turkish->English: requested=40, accepted=41, current=460/583
baggage_and_personal_items::placing cabin bag::Turkish->English: requested=40, accepted=47, current=507/583
baggage_and_personal_items::placing cabin bag::Turkish->English: requested=40, accepted=40, current=547/583
baggage_and_personal_items::placing cabin bag::Turkish->English: requested=36, accepted=38, current=585/583

baggage_and_personal_items / bag does not fit / English->Turkish:   0%|          | 0/583 [00:00<?, ?it/s]

baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=41, current=41/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=44, current=85/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=42, current=127/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=40, current=167/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=41, current=208/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=43, current=251/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=37, current=288/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=42, current=330/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=42, current=372/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=45, current=417/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=39, current=456/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=43, current=499/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=39, current=538/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=40, accepted=41, current=579/583
baggage_and_personal_items::bag does not fit::English->Turkish: requested=4, accepted=4, current=583/583

baggage_and_personal_items / bag does not fit / Turkish->English:   0%|          | 0/583 [00:00<?, ?it/s]

baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=40, current=40/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=41, current=81/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=43, current=124/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=39, current=163/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=41, current=204/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=41, current=245/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=39, current=284/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=42, current=326/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=41, current=367/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=41, current=408/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=43, current=451/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=42, current=493/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=42, current=535/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=40, accepted=42, current=577/583
baggage_and_personal_items::bag does not fit::Turkish->English: requested=6, accepted=6, current=583/583

baggage_and_personal_items / lost phone wallet passport or headphones / English->Turkish:   0%|          | 0/5…

baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=43, current=43/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=40, current=83/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=43, current=126/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=38, current=164/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=41, current=205/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=41, current=246/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=44, current=290/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=41, current=331/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=40, current=371/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=40, current=411/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=41, current=452/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=39, current=491/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=40, current=531/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=40, accepted=43, current=574/583
baggage_and_personal_items::lost phone wallet passport or headphones::English->Turkish: requested=9, accepted=9, current=583/583

baggage_and_personal_items / lost phone wallet passport or headphones / Turkish->English:   0%|          | 0/5…

baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=43, current=43/583
baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=40, current=83/583
baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=40, current=123/583
baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=39, current=162/583
baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=43, current=205/583
baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=42, current=247/583
baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=45, current=292/583
baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=42, current=334/583
baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=40, current=374/583
baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=41, current=415/583
baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=39, current=454/583
baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=40, current=494/583
baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=48, current=542/583
baggage_and_personal_items::lost phone wallet passport or headphones::Turkish->English: requested=40, accepted=50, current=592/583

baggage_and_personal_items / forgotten item on plane / English->Turkish:   0%|          | 0/583 [00:00<?, ?it/…

baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=41, current=41/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=42, current=83/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=40, current=123/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=38, current=161/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=41, current=202/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=41, current=243/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=42, current=285/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=40, current=325/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=39, current=364/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=38, current=402/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=43, current=445/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=45, current=490/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=42, current=532/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=40, accepted=39, current=571/583
baggage_and_personal_items::forgotten item on plane::English->Turkish: requested=12, accepted=12, current=583/583

baggage_and_personal_items / forgotten item on plane / Turkish->English:   0%|          | 0/583 [00:00<?, ?it/…

baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=40, accepted=39, current=39/583
baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=40, accepted=42, current=81/583
baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=40, accepted=49, current=130/583
baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=40, accepted=45, current=175/583
baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=40, accepted=40, current=215/583
baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=40, accepted=43, current=258/583
baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=40, accepted=41, current=299/583
baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=40, accepted=40, current=339/583
baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=40, accepted=41, current=380/583
baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=40, accepted=45, current=425/583
baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=40, accepted=47, current=472/583
baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=40, accepted=39, current=511/583
baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=40, accepted=40, current=551/583
baggage_and_personal_items::forgotten item on plane::Turkish->English: requested=32, accepted=32, current=583/583

baggage_and_personal_items / wrong bag or damaged suitcase / English->Turkish:   0%|          | 0/583 [00:00<?…

baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=38, current=38/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=40, current=78/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=38, current=116/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=40, current=156/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=42, current=198/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=39, current=237/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=40, current=277/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=38, current=315/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=40, current=355/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=41, current=396/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=40, current=436/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=40, current=476/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=43, current=519/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=40, accepted=41, current=560/583
baggage_and_personal_items::wrong bag or damaged suitcase::English->Turkish: requested=23, accepted=23, current=583/583

baggage_and_personal_items / wrong bag or damaged suitcase / Turkish->English:   0%|          | 0/583 [00:00<?…

baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=42, current=42/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=40, current=82/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=42, current=124/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=38, current=162/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=44, current=206/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=38, current=244/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=41, current=285/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=46, current=331/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=40, current=371/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=40, current=411/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=41, current=452/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=39, current=491/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=41, current=532/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=40, accepted=46, current=578/583
baggage_and_personal_items::wrong bag or damaged suitcase::Turkish->English: requested=5, accepted=5, current=583/583

baggage_and_personal_items / lost luggage reporting / English->Turkish:   0%|          | 0/583 [00:00<?, ?it/s…

baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=43, current=43/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=40, current=83/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=39, current=122/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=41, current=163/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=39, current=202/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=41, current=243/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=43, current=286/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=43, current=329/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=39, current=368/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=39, current=407/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=45, current=452/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=38, current=490/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=41, current=531/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=40, accepted=37, current=568/583
baggage_and_personal_items::lost luggage reporting::English->Turkish: requested=15, accepted=15, current=583/583

baggage_and_personal_items / lost luggage reporting / Turkish->English:   0%|          | 0/583 [00:00<?, ?it/s…

baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=39, current=39/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=43, current=82/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=38, current=120/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=40, current=160/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=40, current=200/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=41, current=241/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=40, current=281/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=42, current=323/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=43, current=366/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=40, current=406/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=44, current=450/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=40, current=490/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=37, current=527/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=40, accepted=41, current=568/583
baggage_and_personal_items::lost luggage reporting::Turkish->English: requested=15, accepted=15, current=583/583

children_and_family / traveling with child / English->Turkish:   0%|          | 0/500 [00:00<?, ?it/s]

children_and_family::traveling with child::English->Turkish: requested=40, accepted=38, current=38/500
children_and_family::traveling with child::English->Turkish: requested=40, accepted=43, current=81/500
children_and_family::traveling with child::English->Turkish: requested=40, accepted=40, current=121/500
children_and_family::traveling with child::English->Turkish: requested=40, accepted=38, current=159/500
children_and_family::traveling with child::English->Turkish: requested=40, accepted=42, current=201/500
children_and_family::traveling with child::English->Turkish: requested=40, accepted=42, current=243/500
children_and_family::traveling with child::English->Turkish: requested=40, accepted=44, current=287/500
children_and_family::traveling with child::English->Turkish: requested=40, accepted=41, current=328/500
children_and_family::traveling with child::English->Turkish: requested=40, accepted=41, current=369/500
children_and_family::traveling with child::English->Turkish: requested=40, accepted=40, current=409/500
children_and_family::traveling with child::English->Turkish: requested=40, accepted=42, current=451/500
children_and_family::traveling with child::English->Turkish: requested=40, accepted=37, current=488/500
children_and_family::traveling with child::English->Turkish: requested=12, accepted=12, current=500/500

children_and_family / traveling with child / Turkish->English:   0%|          | 0/500 [00:00<?, ?it/s]

children_and_family::traveling with child::Turkish->English: requested=40, accepted=39, current=39/500
children_and_family::traveling with child::Turkish->English: requested=40, accepted=40, current=79/500
children_and_family::traveling with child::Turkish->English: requested=40, accepted=39, current=118/500
children_and_family::traveling with child::Turkish->English: requested=40, accepted=39, current=157/500
children_and_family::traveling with child::Turkish->English: requested=40, accepted=39, current=196/500
children_and_family::traveling with child::Turkish->English: requested=40, accepted=41, current=237/500
children_and_family::traveling with child::Turkish->English: requested=40, accepted=37, current=274/500
children_and_family::traveling with child::Turkish->English: requested=40, accepted=40, current=314/500
children_and_family::traveling with child::Turkish->English: requested=40, accepted=40, current=354/500
children_and_family::traveling with child::Turkish->English: requested=40, accepted=40, current=394/500
children_and_family::traveling with child::Turkish->English: requested=40, accepted=38, current=432/500
children_and_family::traveling with child::Turkish->English: requested=40, accepted=39, current=471/500
children_and_family::traveling with child::Turkish->English: requested=29, accepted=29, current=500/500

children_and_family / family seating requests / English->Turkish:   0%|          | 0/500 [00:00<?, ?it/s]

children_and_family::family seating requests::English->Turkish: requested=40, accepted=42, current=42/500
children_and_family::family seating requests::English->Turkish: requested=40, accepted=38, current=80/500
children_and_family::family seating requests::English->Turkish: requested=40, accepted=39, current=119/500
children_and_family::family seating requests::English->Turkish: requested=40, accepted=41, current=160/500
children_and_family::family seating requests::English->Turkish: requested=40, accepted=39, current=199/500
children_and_family::family seating requests::English->Turkish: requested=40, accepted=38, current=237/500
children_and_family::family seating requests::English->Turkish: requested=40, accepted=43, current=280/500
children_and_family::family seating requests::English->Turkish: requested=40, accepted=43, current=323/500
children_and_family::family seating requests::English->Turkish: requested=40, accepted=42, current=365/500
children_and_family::family seating requests::English->Turkish: requested=40, accepted=41, current=406/500
children_and_family::family seating requests::English->Turkish: requested=40, accepted=39, current=445/500
children_and_family::family seating requests::English->Turkish: requested=40, accepted=42, current=487/500
children_and_family::family seating requests::English->Turkish: requested=13, accepted=13, current=500/500

children_and_family / family seating requests / Turkish->English:   0%|          | 0/500 [00:00<?, ?it/s]

children_and_family::family seating requests::Turkish->English: requested=40, accepted=39, current=39/500
children_and_family::family seating requests::Turkish->English: requested=40, accepted=40, current=79/500
children_and_family::family seating requests::Turkish->English: requested=40, accepted=37, current=116/500
children_and_family::family seating requests::Turkish->English: requested=40, accepted=38, current=154/500
children_and_family::family seating requests::Turkish->English: requested=40, accepted=40, current=194/500
children_and_family::family seating requests::Turkish->English: requested=40, accepted=39, current=233/500
children_and_family::family seating requests::Turkish->English: requested=40, accepted=39, current=272/500
children_and_family::family seating requests::Turkish->English: requested=40, accepted=40, current=312/500
children_and_family::family seating requests::Turkish->English: requested=40, accepted=40, current=352/500
children_and_family::family seating requests::Turkish->English: requested=40, accepted=43, current=395/500
children_and_family::family seating requests::Turkish->English: requested=40, accepted=50, current=445/500
children_and_family::family seating requests::Turkish->English: requested=40, accepted=38, current=483/500
children_and_family::family seating requests::Turkish->English: requested=17, accepted=17, current=500/500

children_and_family / baby milk and bottle warming / English->Turkish:   0%|          | 0/500 [00:00<?, ?it/s]

children_and_family::baby milk and bottle warming::English->Turkish: requested=40, accepted=37, current=37/500
children_and_family::baby milk and bottle warming::English->Turkish: requested=40, accepted=38, current=75/500
children_and_family::baby milk and bottle warming::English->Turkish: requested=40, accepted=40, current=115/500
children_and_family::baby milk and bottle warming::English->Turkish: requested=40, accepted=38, current=153/500
children_and_family::baby milk and bottle warming::English->Turkish: requested=40, accepted=40, current=193/500
children_and_family::baby milk and bottle warming::English->Turkish: requested=40, accepted=40, current=233/500
children_and_family::baby milk and bottle warming::English->Turkish: requested=40, accepted=38, current=271/500
children_and_family::baby milk and bottle warming::English->Turkish: requested=40, accepted=36, current=307/500
children_and_family::baby milk and bottle warming::English->Turkish: requested=40, accepted=44, current=351/500
children_and_family::baby milk and bottle warming::English->Turkish: requested=40, accepted=40, current=391/500
children_and_family::baby milk and bottle warming::English->Turkish: requested=40, accepted=39, current=430/500
children_and_family::baby milk and bottle warming::English->Turkish: requested=40, accepted=40, current=470/500
children_and_family::baby milk and bottle warming::English->Turkish: requested=30, accepted=29, current=499/500
children_and_family::baby milk and bottle warming::English->Turkish: requested=1, accepted=3, current=502/500

children_and_family / baby milk and bottle warming / Turkish->English:   0%|          | 0/500 [00:00<?, ?it/s]

children_and_family::baby milk and bottle warming::Turkish->English: requested=40, accepted=39, current=39/500
children_and_family::baby milk and bottle warming::Turkish->English: requested=40, accepted=43, current=82/500
children_and_family::baby milk and bottle warming::Turkish->English: requested=40, accepted=42, current=124/500
children_and_family::baby milk and bottle warming::Turkish->English: requested=40, accepted=42, current=166/500
children_and_family::baby milk and bottle warming::Turkish->English: requested=40, accepted=40, current=206/500
children_and_family::baby milk and bottle warming::Turkish->English: requested=40, accepted=63, current=269/500
children_and_family::baby milk and bottle warming::Turkish->English: requested=40, accepted=43, current=312/500
children_and_family::baby milk and bottle warming::Turkish->English: requested=40, accepted=43, current=355/500
children_and_family::baby milk and bottle warming::Turkish->English: requested=40, accepted=40, current=395/500
children_and_family::baby milk and bottle warming::Turkish->English: requested=40, accepted=42, current=437/500
children_and_family::baby milk and bottle warming::Turkish->English: requested=40, accepted=41, current=478/500
children_and_family::baby milk and bottle warming::Turkish->English: requested=22, accepted=22, current=500/500

children_and_family / child meal and baby food / English->Turkish:   0%|          | 0/500 [00:00<?, ?it/s]

children_and_family::child meal and baby food::English->Turkish: requested=40, accepted=50, current=50/500
children_and_family::child meal and baby food::English->Turkish: requested=40, accepted=40, current=90/500
children_and_family::child meal and baby food::English->Turkish: requested=40, accepted=42, current=132/500
children_and_family::child meal and baby food::English->Turkish: requested=40, accepted=41, current=173/500
children_and_family::child meal and baby food::English->Turkish: requested=40, accepted=40, current=213/500
children_and_family::child meal and baby food::English->Turkish: requested=40, accepted=39, current=252/500
children_and_family::child meal and baby food::English->Turkish: requested=40, accepted=40, current=292/500
children_and_family::child meal and baby food::English->Turkish: requested=40, accepted=44, current=336/500
children_and_family::child meal and baby food::English->Turkish: requested=40, accepted=42, current=378/500
children_and_family::child meal and baby food::English->Turkish: requested=40, accepted=50, current=428/500
children_and_family::child meal and baby food::English->Turkish: requested=40, accepted=40, current=468/500
children_and_family::child meal and baby food::English->Turkish: requested=32, accepted=38, current=506/500

children_and_family / child meal and baby food / Turkish->English:   0%|          | 0/500 [00:00<?, ?it/s]

children_and_family::child meal and baby food::Turkish->English: requested=40, accepted=41, current=41/500
children_and_family::child meal and baby food::Turkish->English: requested=40, accepted=43, current=84/500
children_and_family::child meal and baby food::Turkish->English: requested=40, accepted=38, current=122/500
children_and_family::child meal and baby food::Turkish->English: requested=40, accepted=41, current=163/500
children_and_family::child meal and baby food::Turkish->English: requested=40, accepted=40, current=203/500
children_and_family::child meal and baby food::Turkish->English: requested=40, accepted=42, current=245/500
children_and_family::child meal and baby food::Turkish->English: requested=40, accepted=42, current=287/500
children_and_family::child meal and baby food::Turkish->English: requested=40, accepted=43, current=330/500
children_and_family::child meal and baby food::Turkish->English: requested=40, accepted=38, current=368/500
children_and_family::child meal and baby food::Turkish->English: requested=40, accepted=40, current=408/500
children_and_family::child meal and baby food::Turkish->English: requested=40, accepted=44, current=452/500
children_and_family::child meal and baby food::Turkish->English: requested=40, accepted=43, current=495/500
children_and_family::child meal and baby food::Turkish->English: requested=5, accepted=5, current=500/500

children_and_family / child is sick afraid or crying / English->Turkish:   0%|          | 0/500 [00:00<?, ?it/…

children_and_family::child is sick afraid or crying::English->Turkish: requested=40, accepted=41, current=41/500
children_and_family::child is sick afraid or crying::English->Turkish: requested=40, accepted=38, current=79/500
children_and_family::child is sick afraid or crying::English->Turkish: requested=40, accepted=37, current=116/500
children_and_family::child is sick afraid or crying::English->Turkish: requested=40, accepted=41, current=157/500
children_and_family::child is sick afraid or crying::English->Turkish: requested=40, accepted=39, current=196/500
children_and_family::child is sick afraid or crying::English->Turkish: requested=40, accepted=39, current=235/500
children_and_family::child is sick afraid or crying::English->Turkish: requested=40, accepted=40, current=275/500
children_and_family::child is sick afraid or crying::English->Turkish: requested=40, accepted=37, current=312/500
children_and_family::child is sick afraid or crying::English->Turkish: requested=40, accepted=42, current=354/500
children_and_family::child is sick afraid or crying::English->Turkish: requested=40, accepted=41, current=395/500
children_and_family::child is sick afraid or crying::English->Turkish: requested=40, accepted=41, current=436/500
children_and_family::child is sick afraid or crying::English->Turkish: requested=40, accepted=39, current=475/500
children_and_family::child is sick afraid or crying::English->Turkish: requested=25, accepted=24, current=499/500
children_and_family::child is sick afraid or crying::English->Turkish: requested=1, accepted=1, current=500/500

children_and_family / child is sick afraid or crying / Turkish->English:   0%|          | 0/500 [00:00<?, ?it/…

children_and_family::child is sick afraid or crying::Turkish->English: requested=40, accepted=41, current=41/500
children_and_family::child is sick afraid or crying::Turkish->English: requested=40, accepted=40, current=81/500
children_and_family::child is sick afraid or crying::Turkish->English: requested=40, accepted=41, current=122/500
children_and_family::child is sick afraid or crying::Turkish->English: requested=40, accepted=42, current=164/500
children_and_family::child is sick afraid or crying::Turkish->English: requested=40, accepted=37, current=201/500
children_and_family::child is sick afraid or crying::Turkish->English: requested=40, accepted=41, current=242/500
children_and_family::child is sick afraid or crying::Turkish->English: requested=40, accepted=38, current=280/500
children_and_family::child is sick afraid or crying::Turkish->English: requested=40, accepted=41, current=321/500
children_and_family::child is sick afraid or crying::Turkish->English: requested=40, accepted=42, current=363/500
children_and_family::child is sick afraid or crying::Turkish->English: requested=40, accepted=41, current=404/500
children_and_family::child is sick afraid or crying::Turkish->English: requested=40, accepted=39, current=443/500
children_and_family::child is sick afraid or crying::Turkish->English: requested=40, accepted=40, current=483/500
children_and_family::child is sick afraid or crying::Turkish->English: requested=17, accepted=17, current=500/500

children_and_family / stroller and diaper change needs / English->Turkish:   0%|          | 0/500 [00:00<?, ?i…

children_and_family::stroller and diaper change needs::English->Turkish: requested=40, accepted=43, current=43/500
children_and_family::stroller and diaper change needs::English->Turkish: requested=40, accepted=41, current=84/500
children_and_family::stroller and diaper change needs::English->Turkish: requested=40, accepted=42, current=126/500
children_and_family::stroller and diaper change needs::English->Turkish: requested=40, accepted=40, current=166/500
children_and_family::stroller and diaper change needs::English->Turkish: requested=40, accepted=45, current=211/500
children_and_family::stroller and diaper change needs::English->Turkish: requested=40, accepted=40, current=251/500
children_and_family::stroller and diaper change needs::English->Turkish: requested=40, accepted=39, current=290/500
children_and_family::stroller and diaper change needs::English->Turkish: requested=40, accepted=43, current=333/500
children_and_family::stroller and diaper change needs::English->Turkish: requested=40, accepted=42, current=375/500
children_and_family::stroller and diaper change needs::English->Turkish: requested=40, accepted=50, current=425/500
children_and_family::stroller and diaper change needs::English->Turkish: requested=40, accepted=40, current=465/500
children_and_family::stroller and diaper change needs::English->Turkish: requested=35, accepted=38, current=503/500

children_and_family / stroller and diaper change needs / Turkish->English:   0%|          | 0/500 [00:00<?, ?i…

children_and_family::stroller and diaper change needs::Turkish->English: requested=40, accepted=43, current=43/500
children_and_family::stroller and diaper change needs::Turkish->English: requested=40, accepted=40, current=83/500
children_and_family::stroller and diaper change needs::Turkish->English: requested=40, accepted=50, current=133/500
children_and_family::stroller and diaper change needs::Turkish->English: requested=40, accepted=40, current=173/500
children_and_family::stroller and diaper change needs::Turkish->English: requested=40, accepted=37, current=210/500
children_and_family::stroller and diaper change needs::Turkish->English: requested=40, accepted=46, current=256/500
children_and_family::stroller and diaper change needs::Turkish->English: requested=40, accepted=42, current=298/500
children_and_family::stroller and diaper change needs::Turkish->English: requested=40, accepted=41, current=339/500
children_and_family::stroller and diaper change needs::Turkish->English: requested=40, accepted=39, current=378/500
children_and_family::stroller and diaper change needs::Turkish->English: requested=40, accepted=38, current=416/500
children_and_family::stroller and diaper change needs::Turkish->English: requested=40, accepted=41, current=457/500
children_and_family::stroller and diaper change needs::Turkish->English: requested=40, accepted=40, current=497/500
children_and_family::stroller and diaper change needs::Turkish->English: requested=3, accepted=3, current=500/500

pets_and_service_animals / traveling with pet in cabin / English->Turkish:   0%|          | 0/291 [00:00<?, ?i…

pets_and_service_animals::traveling with pet in cabin::English->Turkish: requested=40, accepted=44, current=44/291
pets_and_service_animals::traveling with pet in cabin::English->Turkish: requested=40, accepted=45, current=89/291
pets_and_service_animals::traveling with pet in cabin::English->Turkish: requested=40, accepted=39, current=128/291
pets_and_service_animals::traveling with pet in cabin::English->Turkish: requested=40, accepted=42, current=170/291
pets_and_service_animals::traveling with pet in cabin::English->Turkish: requested=40, accepted=40, current=210/291
pets_and_service_animals::traveling with pet in cabin::English->Turkish: requested=40, accepted=41, current=251/291
pets_and_service_animals::traveling with pet in cabin::English->Turkish: requested=40, accepted=42, current=293/291

pets_and_service_animals / traveling with pet in cabin / Turkish->English:   0%|          | 0/291 [00:00<?, ?i…

pets_and_service_animals::traveling with pet in cabin::Turkish->English: requested=40, accepted=42, current=42/291
pets_and_service_animals::traveling with pet in cabin::Turkish->English: requested=40, accepted=40, current=82/291
pets_and_service_animals::traveling with pet in cabin::Turkish->English: requested=40, accepted=39, current=121/291
pets_and_service_animals::traveling with pet in cabin::Turkish->English: requested=40, accepted=43, current=164/291
pets_and_service_animals::traveling with pet in cabin::Turkish->English: requested=40, accepted=41, current=205/291
pets_and_service_animals::traveling with pet in cabin::Turkish->English: requested=40, accepted=40, current=245/291
pets_and_service_animals::traveling with pet in cabin::Turkish->English: requested=40, accepted=42, current=287/291
pets_and_service_animals::traveling with pet in cabin::Turkish->English: requested=4, accepted=4, current=291/291

pets_and_service_animals / service animal explanation / English->Turkish:   0%|          | 0/291 [00:00<?, ?it…

pets_and_service_animals::service animal explanation::English->Turkish: requested=40, accepted=43, current=43/291
pets_and_service_animals::service animal explanation::English->Turkish: requested=40, accepted=40, current=83/291
pets_and_service_animals::service animal explanation::English->Turkish: requested=40, accepted=40, current=123/291
pets_and_service_animals::service animal explanation::English->Turkish: requested=40, accepted=41, current=164/291
pets_and_service_animals::service animal explanation::English->Turkish: requested=40, accepted=39, current=203/291
pets_and_service_animals::service animal explanation::English->Turkish: requested=40, accepted=41, current=244/291
pets_and_service_animals::service animal explanation::English->Turkish: requested=40, accepted=38, current=282/291
pets_and_service_animals::service animal explanation::English->Turkish: requested=9, accepted=9, current=291/291

pets_and_service_animals / service animal explanation / Turkish->English:   0%|          | 0/291 [00:00<?, ?it…

pets_and_service_animals::service animal explanation::Turkish->English: requested=40, accepted=41, current=41/291
pets_and_service_animals::service animal explanation::Turkish->English: requested=40, accepted=42, current=83/291
pets_and_service_animals::service animal explanation::Turkish->English: requested=40, accepted=40, current=123/291
pets_and_service_animals::service animal explanation::Turkish->English: requested=40, accepted=40, current=163/291
pets_and_service_animals::service animal explanation::Turkish->English: requested=40, accepted=41, current=204/291
pets_and_service_animals::service animal explanation::Turkish->English: requested=40, accepted=37, current=241/291
pets_and_service_animals::service animal explanation::Turkish->English: requested=40, accepted=37, current=278/291
pets_and_service_animals::service animal explanation::Turkish->English: requested=13, accepted=13, current=291/291

pets_and_service_animals / pet carrier under seat / English->Turkish:   0%|          | 0/291 [00:00<?, ?it/s]

pets_and_service_animals::pet carrier under seat::English->Turkish: requested=40, accepted=39, current=39/291
pets_and_service_animals::pet carrier under seat::English->Turkish: requested=40, accepted=40, current=79/291
pets_and_service_animals::pet carrier under seat::English->Turkish: requested=40, accepted=39, current=118/291
pets_and_service_animals::pet carrier under seat::English->Turkish: requested=40, accepted=43, current=161/291
pets_and_service_animals::pet carrier under seat::English->Turkish: requested=40, accepted=38, current=199/291
pets_and_service_animals::pet carrier under seat::English->Turkish: requested=40, accepted=39, current=238/291
pets_and_service_animals::pet carrier under seat::English->Turkish: requested=40, accepted=43, current=281/291
pets_and_service_animals::pet carrier under seat::English->Turkish: requested=10, accepted=10, current=291/291

pets_and_service_animals / pet carrier under seat / Turkish->English:   0%|          | 0/291 [00:00<?, ?it/s]

pets_and_service_animals::pet carrier under seat::Turkish->English: requested=40, accepted=40, current=40/291
pets_and_service_animals::pet carrier under seat::Turkish->English: requested=40, accepted=42, current=82/291
pets_and_service_animals::pet carrier under seat::Turkish->English: requested=40, accepted=41, current=123/291
pets_and_service_animals::pet carrier under seat::Turkish->English: requested=40, accepted=40, current=163/291
pets_and_service_animals::pet carrier under seat::Turkish->English: requested=40, accepted=42, current=205/291
pets_and_service_animals::pet carrier under seat::Turkish->English: requested=40, accepted=43, current=248/291
pets_and_service_animals::pet carrier under seat::Turkish->English: requested=40, accepted=40, current=288/291
pets_and_service_animals::pet carrier under seat::Turkish->English: requested=3, accepted=3, current=291/291

pets_and_service_animals / pet is anxious / English->Turkish:   0%|          | 0/291 [00:00<?, ?it/s]

pets_and_service_animals::pet is anxious::English->Turkish: requested=40, accepted=44, current=44/291

In [26]:
def load_all_chunk_examples() -> list[TranslationExample]:
    all_examples = []

    for path in sorted(CHUNK_DIR.glob("*.jsonl")):
        all_examples.extend(read_jsonl_examples(path))

    all_examples = basic_quality_filter(all_examples)
    all_examples = dedupe_examples(all_examples)

    return all_examples


merged_examples = load_all_chunk_examples()

print("Merged example count:", len(merged_examples))

Merged example count: 50256

In [27]:
def save_raw_merged_jsonl(examples: list[TranslationExample]) -> None:
    with RAW_MERGED_JSONL_PATH.open("w", encoding="utf-8") as file:
        for example in examples:
            file.write(example.model_dump_json() + "\n")


def save_merged_csv(examples: list[TranslationExample]) -> None:
    rows = []

    for example in examples:
        row = example.model_dump()
        row["tags"] = ",".join(example.tags)
        rows.append(row)

    df = pd.DataFrame(rows)
    df.to_csv(CSV_MERGED_PATH, index=False, encoding="utf-8")


save_raw_merged_jsonl(merged_examples)
save_merged_csv(merged_examples)

print(RAW_MERGED_JSONL_PATH)
print(CSV_MERGED_PATH)

/content/airplane_translation_dataset/final/raw_pairs_merged.jsonl
/content/airplane_translation_dataset/final/pairs_merged.csv

In [28]:
TRANSLATION_SYSTEM_PROMPT = """You are a Turkish-English translation assistant specialized in airplane, airport boarding, cabin, passenger, and flight-related situations.

Your task is to translate the user's sentence between Turkish and English.

Rules:
- If the input is Turkish, translate it into natural English.
- If the input is English, translate it into natural Turkish.
- Preserve the meaning, politeness level, urgency, and speaker intent.
- Use simple, clear, practical language suitable for airplane passengers and cabin crew.
- Do not add explanations.
- Do not answer the user's request.
- Do not roleplay.
- Only return the translated sentence.
- For emergency sentences, keep the translation direct and accurate.
- For polite requests, preserve politeness naturally.
- For announcements or crew instructions, use clear formal language.
"""


def build_fine_tune_record(example: TranslationExample) -> dict:
    instruction = (
        "Translate to Turkish:"
        if example.target_language == "Turkish"
        else "Translate to English:"
    )

    return {
        "messages": [
            {
                "role": "system",
                "content": TRANSLATION_SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": f"{instruction} {example.source_text}",
            },
            {
                "role": "assistant",
                "content": example.target_text,
            },
        ],
        "metadata": {
            "domain": example.domain,
            "scenario_group": example.scenario_group,
            "difficulty": example.difficulty,
            "tone": example.tone,
            "speaker": example.speaker,
            "listener": example.listener,
        },
    }


with FINE_TUNE_JSONL_PATH.open("w", encoding="utf-8") as file:
    for example in merged_examples:
        file.write(json.dumps(build_fine_tune_record(example), ensure_ascii=False) + "\n")

print(FINE_TUNE_JSONL_PATH)

/content/airplane_translation_dataset/final/fine_tune_chat.jsonl

In [29]:
df = pd.read_csv(CSV_MERGED_PATH)

print("Total:", len(df))

display(df.groupby("domain").size().sort_values(ascending=False))
display(df.groupby(["domain", "scenario_group"]).size().sort_values(ascending=False).head(50))
display(df.groupby(["source_language", "target_language"]).size())
display(df.groupby("difficulty").size())
display(df.groupby("tone").size())
display(df.groupby(["speaker", "listener"]).size().sort_values(ascending=False).head(30))

Total: 50256

domain
food_and_drink                      8055
flight_time_delay_and_arrival       7377
seat_and_cabin_location             7253
baggage_and_personal_items          6634
comfort_and_cabin_needs             6403
children_and_family                 5615
toilet_and_lavatory                 4491
greetings_and_basic_conversation    2693
pets_and_service_animals            1735
dtype: int64

domain                            scenario_group
flight_time_delay_and_arrival     local time at destination                       1299
                                  connecting flight concerns                      1282
seat_and_cabin_location           finding assigned seat                           1233
                                  family sitting together                         1233
flight_time_delay_and_arrival     gate and baggage claim after landing            1229
seat_and_cabin_location           overhead bin and under-seat bag placement       1226
flight_time_delay_and_arrival     asking arrival and landing time                 1217
seat_and_cabin_location           seatbelt and aisle clearance instructions       1209
                                  window aisle and middle seat requests           1205
food_and_drink                    special meal already ordered                    1185
                                  meal choice chicken beef fish pasta             1176
flight_time_delay_and_arrival     asking flight duration                          1176
                                  delay and waiting explanations                  1174
food_and_drink                    complaining about cold or missing food          1171
                                  food allergy warnings                           1168
                                  asking for bread napkin or extra drink          1149
seat_and_cabin_location           someone sitting in passenger seat               1147
baggage_and_personal_items        bag does not fit                                1136
                                  forgotten item on plane                         1132
                                  placing cabin bag                               1129
food_and_drink                    vegetarian vegan halal and dietary requests     1122
comfort_and_cabin_needs           asking for sick bag                             1098
baggage_and_personal_items        lost luggage reporting                          1090
comfort_and_cabin_needs           seat recline or broken seat                     1090
                                  feeling cold or hot                             1085
food_and_drink                    asking for water tea coffee or juice            1084
comfort_and_cabin_needs           air vent reading light and tray table           1084
baggage_and_personal_items        lost phone wallet passport or headphones        1077
                                  wrong bag or damaged suitcase                   1070
comfort_and_cabin_needs           asking for blanket or pillow                    1062
                                  screen headphones and entertainment problems     984
children_and_family               family seating requests                          981
                                  stroller and diaper change needs                 956
                                  child meal and baby food                         955
                                  baby milk and bottle warming                     933
                                  child is sick afraid or crying                   925
                                  traveling with child                             865
toilet_and_lavatory               seatbelt sign and toilet restriction             806
                                  toilet occupied or unavailable                   783
                                  asking permission to use the toilet              767
                                  urgent toilet need                               728
                                  asking where the toilet is                       721
                                  toilet problem reporting                         686
greetings_and_basic_conversation  asking someone to repeat slowly                  572
pets_and_service_animals          pet carrier under seat                           571
                                  traveling with pet in cabin                      563
                                  service animal explanation                       557
greetings_and_basic_conversation  asking for help                                  556
                                  simple misunderstanding phrases                  556
                                  saying thank you and goodbye                     524
dtype: int64

source_language  target_language
English          Turkish            24485
Turkish          English            25771
dtype: int64

difficulty
A1    15365
A2    26794
B1     8097
dtype: int64

tone
formal         2918
neutral       17698
polite        21480
reassuring     4295
urgent         3865
dtype: int64

speaker        listener
passenger      cabin_crew       23596
cabin_crew     passenger        11297
passenger      airport_staff     9682
airport_staff  passenger         4255
passenger      gate_agent         807
               passenger          238
cabin_crew     cabin_crew         156
gate_agent     passenger           94
pilot          passenger           52
passenger      pilot               31
airport_staff  cabin_crew          19
cabin_crew     airport_staff       14
               pilot                8
airport_staff  airport_staff        5
pilot          cabin_crew           2
dtype: int64

In [30]:
progress = load_progress()

underfilled = []

for key, value in progress.items():
    if value["current_count"] < value["target_count"]:
        underfilled.append(
            {
                "key": key,
                "current_count": value["current_count"],
                "target_count": value["target_count"],
                "missing": value["target_count"] - value["current_count"],
                "status": value["status"],
            }
        )

underfilled_df = pd.DataFrame(underfilled)

if len(underfilled_df):
    display(underfilled_df.sort_values("missing", ascending=False))
else:
    print("No underfilled chunks.")

,key,current_count,target_count,missing,status
0,pets_and_service_animals::pet is anxious::Engl...,44,291,247,running

In [31]:
import shutil
from google.colab import files

ZIP_PATH = "/content/airplane_translation_dataset.zip"

shutil.make_archive(
    base_name=ZIP_PATH.replace(".zip", ""),
    format="zip",
    root_dir=str(EXPORT_DIR),
)

files.download(ZIP_PATH)